/** Opções extras para os temas do Leilão (somadas às originais, sem repetir). */
export const FREE_EXTRAS: Record<string, string[]> = {
  marcas: ["Zara", "Lacoste", "Puma", "Balenciaga", "Tommy Hilfiger", "Calvin Klein", "Levi's", "Oakley", "Ray-Ban", "Vans", "Converse", "Hering"],
  filmes: ["Interestelar", "O Poderoso Chefão", "Clube da Luta", "Matrix", "Forrest Gump", "Gladiador", "Coringa", "Parasita", "A Origem", "Pulp Fiction", "Toy Story", "O Rei Leão"],
  series: ["Breaking Bad", "Stranger Things", "Game of Thrones", "The Office", "Friends", "Dark", "La Casa de Papel", "The Boys", "Wandinha", "Round 6", "The Last of Us", "Peaky Blinders", "Grey's Anatomy", "Suits"],
  animes: ["Naruto", "One Piece", "Attack on Titan", "Death Note", "Demon Slayer", "Jujutsu Kaisen", "Dragon Ball Z", "Fullmetal Alchemist", "Hunter x Hunter", "My Hero Academia", "Bleach", "Tokyo Ghoul", "Spy x Family", "Chainsaw Man"],
  cantores: ["Anitta", "Ludmilla", "Gusttavo Lima", "Marília Mendonça", "Jorge & Mateus", "Luan Santana", "Ivete Sangalo", "Caetano Veloso", "Djavan", "Roberto Carlos", "Pabllo Vittar", "Matuê", "L7nnon", "Ana Castela"],
  internacionais: ["Taylor Swift", "Beyoncé", "Drake", "The Weeknd", "Bruno Mars", "Rihanna", "Ed Sheeran", "Billie Eilish", "Dua Lipa", "Justin Bieber", "Ariana Grande", "Kendrick Lamar", "Bad Bunny", "Harry Styles"],
  bandas: ["Queen", "The Beatles", "Coldplay", "Linkin Park", "Imagine Dragons", "Metallica", "AC/DC", "Nirvana", "Maroon 5", "Arctic Monkeys", "Legião Urbana", "Charlie Brown Jr.", "Paralamas do Sucesso", "BTS"],
  comidas: ["Pizza", "Hambúrguer", "Sushi", "Lasanha", "Feijoada", "Churrasco", "Coxinha", "Pastel", "Strogonoff", "Tacos", "Yakisoba", "Parmegiana", "Açaí", "Pão de queijo"],
  sobremesas: ["Pudim", "Brigadeiro", "Petit gâteau", "Tiramisù", "Cheesecake", "Mousse de maracujá", "Torta de limão", "Churros", "Sorvete", "Pavê", "Brownie", "Banoffee", "Romeu e Julieta", "Quindim"],
  carros: ["Ferrari", "Lamborghini", "Porsche 911", "BMW M3", "Mercedes AMG", "Audi R8", "Mustang", "Camaro", "Civic Type R", "Golf GTI", "Tesla Model S", "Bugatti Chiron", "McLaren", "Jeep Compass"],
  cidades: ["Paris", "Nova York", "Tóquio", "Londres", "Roma", "Barcelona", "Dubai", "Rio de Janeiro", "Lisboa", "Amsterdã", "Seul", "Sydney", "Buenos Aires", "Istambul"],
  paises: ["Japão", "Itália", "França", "Canadá", "Austrália", "Suíça", "Grécia", "Portugal", "México", "Noruega", "Coreia do Sul", "Tailândia", "Islândia", "Argentina"],
  praias: ["Fernando de Noronha", "Jericoacoara", "Maragogi", "Bora Bora", "Maldivas", "Cancún", "Porto de Galinhas", "Arraial do Cabo", "Ilha Grande", "Santorini", "Bali", "Copacabana", "Trancoso", "Tulum"],
  animais: ["Leão", "Tigre", "Lobo", "Águia", "Golfinho", "Tubarão", "Panda", "Elefante", "Gato", "Cachorro", "Coruja", "Raposa", "Urso polar", "Onça-pintada"],
  superherois: ["Homem de Ferro", "Batman", "Superman", "Homem-Aranha", "Mulher-Maravilha", "Thor", "Capitão América", "Flash", "Wolverine", "Pantera Negra", "Doutor Estranho", "Aquaman", "Hulk", "Feiticeira Escarlate"],
  viloes: ["Thanos", "Coringa", "Darth Vader", "Voldemort", "Loki", "Magneto", "Hannibal Lecter", "Scar", "Freeza", "Madara", "Sauron", "Bane", "Pennywise", "Dio Brando"],
  jogos: ["GTA V", "Minecraft", "Fortnite", "FIFA", "Free Fire", "Valorant", "League of Legends", "The Last of Us", "God of War", "Red Dead Redemption 2", "Zelda", "Mario Kart", "Call of Duty", "Roblox"],
  apps: ["WhatsApp", "Instagram", "TikTok", "Spotify", "YouTube", "Netflix", "Uber", "iFood", "Pinterest", "Twitter/X", "Discord", "Telegram", "Google Maps", "Nubank"],
  profissoes: ["Médico", "Advogado", "Engenheiro", "Piloto", "Chef", "Programador", "Arquiteto", "Designer", "Astronauta", "Jogador de futebol", "Youtuber", "Dentista", "Psicólogo", "Policial"],
  superpoderes: ["Voar", "Teletransporte", "Invisibilidade", "Ler mentes", "Viajar no tempo", "Superforça", "Supervelocidade", "Imortalidade", "Controlar o fogo", "Respirar debaixo d'água", "Cura instantânea", "Mudar de forma", "Parar o tempo", "Telecinese"],
  esportes: ["Futebol", "Basquete", "Vôlei", "Tênis", "Natação", "Surfe", "Skate", "MMA", "Boxe", "Fórmula 1", "Handebol", "Atletismo", "Ginástica", "Jiu-jitsu"],
  atletas: ["Pelé", "Messi", "Cristiano Ronaldo", "Neymar", "Michael Jordan", "LeBron James", "Usain Bolt", "Serena Williams", "Ayrton Senna", "Rebeca Andrade", "Michael Phelps", "Rafael Nadal", "Roger Federer", "Anderson Silva"],
  youtubers: ["Felipe Neto", "Whindersson Nunes", "Luccas Neto", "Casimiro", "Enaldinho", "Rezendeevil", "Authentic Games", "MrBeast", "PewDiePie", "Manual do Mundo", "Porta dos Fundos", "Julio Cocielo", "Kéfera", "T3ddy"],
  desenhos: ["Bob Esponja", "Os Simpsons", "Pica-Pau", "Tom e Jerry", "Scooby-Doo", "Hora de Aventura", "Apenas um Show", "Ben 10", "Phineas e Ferb", "As Meninas Superpoderosas", "Padrinhos Mágicos", "Avatar", "Gumball", "Pokémon"],
  disney: ["Frozen", "Moana", "Enrolados", "Aladdin", "A Bela e a Fera", "A Pequena Sereia", "Encanto", "Divertida Mente", "Up", "Procurando Nemo", "Viva", "Zootopia", "Lilo & Stitch", "Mulan"],
  doces: ["Kit Kat", "Bis", "Sonho de Valsa", "Ouro Branco", "Prestígio", "Chokito", "Diamante Negro", "Kinder Ovo", "Nutella", "Paçoca", "Trident", "Fini", "Mentos", "Twix"],
  bebidas: ["Coca-Cola", "Guaraná", "Suco de laranja", "Café", "Chá gelado", "Milkshake", "Açaí batido", "Água de coco", "Limonada suíça", "Chocolate quente", "Red Bull", "Toddynho", "Frappuccino", "Caldo de cana"],
  mangas: ["Berserk", "Vagabond", "One Piece", "Naruto", "Chainsaw Man", "Tokyo Revengers", "Vinland Saga", "Slam Dunk", "Monster", "Blue Lock", "Solo Leveling", "Kingdom", "Dorohedoro", "Haikyuu!!"],
  tecnologia: ["iPhone", "PlayStation 5", "MacBook", "AirPods", "Apple Watch", "Nintendo Switch", "Xbox Series X", "iPad", "Kindle", "GoPro", "Drone DJI", "Galaxy S", "Óculos VR", "Alexa"],
  materias: ["Matemática", "Português", "História", "Geografia", "Biologia", "Química", "Física", "Inglês", "Educação Física", "Artes", "Filosofia", "Sociologia", "Espanhol", "Redação"],
  emojis: ["😂", "❤️", "😍", "🥺", "😭", "🔥", "😎", "🤡", "💀", "🙄", "😘", "🤔", "👀", "🥰"],
  redes: ["Instagram", "TikTok", "YouTube", "Twitter/X", "Facebook", "Snapchat", "Pinterest", "Reddit", "Twitch", "Discord", "LinkedIn", "Threads", "Kwai", "BeReal"],
  filmesbr: ["Cidade de Deus", "Tropa de Elite", "O Auto da Compadecida", "Central do Brasil", "Minha Mãe é uma Peça", "Se Eu Fosse Você", "De Pernas pro Ar", "Bacurau", "Que Horas Ela Volta?", "Ainda Estou Aqui", "Carandiru", "Lisbela e o Prisioneiro", "O Palhaço", "Meu Nome Não é Johnny"],
  novelas: ["Avenida Brasil", "O Clone", "Senhora do Destino", "Mulheres Apaixonadas", "Da Cor do Pecado", "Caminho das Índias", "Pantanal", "Carrossel", "Chiquititas", "Malhação", "Rebelde", "Cheias de Charme", "Totalmente Demais", "Verdades Secretas"],
  lugares: ["Torre Eiffel", "Cristo Redentor", "Coliseu", "Machu Picchu", "Muralha da China", "Grand Canyon", "Pirâmides de Gizé", "Cataratas do Iguaçu", "Times Square", "Disney", "Monte Fuji", "Taj Mahal", "Big Ben", "Lençóis Maranhenses"],
  historicos: ["Napoleão", "Cleópatra", "Albert Einstein", "Leonardo da Vinci", "Dom Pedro II", "Tiradentes", "Martin Luther King", "Nelson Mandela", "Marie Curie", "Júlio César", "Santos Dumont", "Isaac Newton", "Gandhi", "Frida Kahlo"],
  bilionarios: ["Elon Musk", "Jeff Bezos", "Bill Gates", "Mark Zuckerberg", "Warren Buffett", "Bernard Arnault", "Larry Page", "Jorge Paulo Lemann", "Rihanna", "Jay-Z", "Taylor Swift", "Kylie Jenner", "Oprah Winfrey", "Steve Jobs"],
  monstros: ["Godzilla", "King Kong", "Drácula", "Frankenstein", "Lobisomem", "Kraken", "Chupa-Cabra", "Pé Grande", "Alien", "Predador", "Slender Man", "Medusa", "Mula sem Cabeça", "Cuca"],
  times: ["Flamengo", "Corinthians", "Palmeiras", "São Paulo", "Santos", "Vasco", "Grêmio", "Internacional", "Real Madrid", "Barcelona", "Manchester City", "Liverpool", "PSG", "Bayern de Munique"],
  musicas: ["Evidências", "Garota de Ipanema", "Bohemian Rhapsody", "Billie Jean", "Blinding Lights", "Despacito", "Envolver", "Leão", "Aquarela", "País do Futebol", "Someone Like You", "Imagine", "Flowers", "Anna Júlia"],
};

/** Extras de futebol por tema: [goleiros, defensores, meias, atacantes]. */
export const FUT_EXTRAS: Record<string, [string[], string[], string[], string[]]> = {
  "fut-lendas": [["Zoff", "Lev Yashin", "Van der Sar", "Marcos"], ["Maldini", "Beckenbauer", "Cafu", "Roberto Carlos", "Cannavaro", "Lúcio", "Baresi"], ["Zidane", "Pirlo", "Xavi", "Iniesta", "Kaká", "Rivaldo", "Zico", "Platini"], ["Pelé", "Ronaldo Fenômeno", "Romário", "Maradona", "Eusébio", "Henry"]],
  "fut-atuais": [["Alisson", "Ederson", "Courtois", "Ter Stegen", "Donnarumma"], ["Van Dijk", "Marquinhos", "Rúben Dias", "Saliba", "Hakimi", "Militão"], ["Bellingham", "De Bruyne", "Rodri", "Pedri", "Valverde", "Odegaard", "Musiala"], ["Haaland", "Mbappé", "Vini Jr.", "Salah", "Kane", "Lautaro"]],
  "fut-brasileirao": [["Weverton", "Cássio", "Rossi", "Fábio", "Hugo Souza"], ["Gustavo Gómez", "Léo Ortiz", "Fabrício Bruno", "Arana", "Murilo"], ["Arrascaeta", "Raphael Veiga", "Gerson", "Lucas Moura", "Garro", "Payet"], ["Pedro", "Hulk", "Estêvão", "Yuri Alberto", "Calleri", "Luiz Araújo"]],
  "fut-seleção": [["Alisson", "Ederson", "Bento", "Weverton"], ["Marquinhos", "Militão", "Gabriel Magalhães", "Danilo", "Thiago Silva"], ["Casemiro", "Bruno Guimarães", "Lucas Paquetá", "André", "Gerson"], ["Vini Jr.", "Rodrygo", "Raphinha", "Neymar", "Endrick", "Richarlison"]],
  "fut-europa": [["Oblak", "Neuer", "Maignan", "Raya"], ["Rüdiger", "Kimmich", "Alexander-Arnold", "Theo Hernández", "Grimaldo"], ["Kroos", "Modrić", "Wirtz", "Foden", "Barella", "Rice"], ["Lewandowski", "Saka", "Kvaratskhelia", "Yamal", "Osimhen"]],
  "fut-futsal": [["Guitta", "Tiago", "Djony", "Willian"], ["Rodrigo", "Marlon", "Pito", "Dyego"], ["Ricardinho", "Ferrão", "Leandro Lino", "Rafa Santos", "Gadeia"], ["Falcão", "Manoel Tobias", "Lenísio", "Neto"]],
  "fut-camisa10": [["Rogério Ceni", "Marcos", "Júlio César", "Dida"], ["Lúcio", "Juan", "Aldair", "Maicon"], ["Ronaldinho", "Zico", "Rivaldo", "Kaká", "Alex", "Djalminha"], ["Neymar", "Messi", "Maradona", "Romário", "Adriano"]],
};
