/**
 * Temas do jogo "Leilão".
 * Temas de futebol montam esquadrão por posição (1 GOL, 1 DEF, 2 MEI, 1 ATA).
 * Os outros temas sorteiam 5 itens livres do mesmo pool.
 */

export type LeilaoTheme = {
  id: string;
  name: string;
  emoji: string;
  slots: string[];
  /** pools[i] = candidatos do slot i (futebol) ou pool único (livre) */
  pools: string[][];
};

const FREE_SLOTS = ["Escolha 1", "Escolha 2", "Escolha 3", "Escolha 4", "Escolha 5"];
const FUT_SLOTS = ["Goleiro", "Defensor", "Meio-campo", "Meio-campo", "Atacante"];

function free(id: string, name: string, emoji: string, items: string[]): LeilaoTheme {
  return { id, name, emoji, slots: FREE_SLOTS, pools: [items] };
}

function fut(
  id: string,
  name: string,
  emoji: string,
  gk: string[],
  def: string[],
  mid: string[],
  att: string[],
): LeilaoTheme {
  return { id, name, emoji, slots: FUT_SLOTS, pools: [gk, def, mid, mid, att] };
}

export const THEMES: LeilaoTheme[] = [
  // ===== FUTEBOL (por posição) =====
  fut(
    "fut-lendas",
    "Lendas do futebol",
    "🏆",
    ["Buffon", "Iker Casillas", "Oliver Kahn", "Dida", "Taffarel", "Peter Schmeichel", "Chilavert"],
    [
      "Cafu",
      "Roberto Carlos",
      "Paolo Maldini",
      "Fabio Cannavaro",
      "Lúcio",
      "Puyol",
      "Nesta",
      "Junior Baiano",
    ],
    [
      "Zidane",
      "Ronaldinho Gaúcho",
      "Xavi",
      "Iniesta",
      "Kaká",
      "Rivaldo",
      "Pirlo",
      "Gerrard",
      "Juninho Pernambucano",
      "Deco",
    ],
    ["Ronaldo Fenômeno", "Romário", "Van Basten", "Henry", "Raúl", "Eusébio", "Batistuta"],
  ),
  fut(
    "fut-atuais",
    "Craques da atualidade",
    "⚽",
    ["Ederson", "Alisson", "Courtois", "Donnarumma", "Ter Stegen", "Weverton", "Rossi"],
    [
      "Van Dijk",
      "Rúben Dias",
      "Militão",
      "Marquinhos",
      "Gabriel Magalhães",
      "Wendell",
      "Arana",
      "Hakimi",
    ],
    [
      "De Bruyne",
      "Bellingham",
      "Rodri",
      "Valverde",
      "Bruno Guimarães",
      "André",
      "Raphael Veiga",
      "Lucas Paquetá",
      "Pedro Rocha",
      "Bitello",
    ],
    [
      "Mbappé",
      "Vini Jr",
      "Haaland",
      "Rodrygo",
      "Lautaro",
      "Yuri Alberto",
      "Pedro",
      "Estêvão",
      "Endrick",
    ],
  ),
  fut(
    "fut-brasileirao",
    "Brasileirão",
    "🇧🇷",
    ["Weverton", "Cássio", "Rafael (SPFC)", "Everson", "John", "Fábio", "Léo Jardim"],
    ["Fagner", "Wesley", "Léo Ortiz", "Murilo", "Guilherme Arana", "Alex Telles", "Vitão"],
    [
      "Raphael Veiga",
      "Hulk",
      "Ganso",
      "Gerson",
      "Zé Rafael",
      "Nikão",
      "Rodriguinho",
      "Alex Santana",
    ],
    ["Pedro", "Yuri Alberto", "Rony", "Cano", "Calleri", "Gabigol", "Everaldo"],
  ),
  fut(
    "fut-seleção",
    "Seleção Brasileira histórica",
    "🟡",
    ["Taffarel", "Marcos", "Dida", "Julio Cesar", "Alisson", "Gilmar"],
    ["Cafu", "Roberto Carlos", "Lúcio", "Aldair", "Thiago Silva", "Marquinhos", "Djalma Santos"],
    [
      "Rivelino",
      "Sócrates",
      "Zico",
      "Ronaldinho",
      "Kaká",
      "Dunga",
      "Gilberto Silva",
      "Casemiro",
      "Falcão",
    ],
    ["Pelé", "Romário", "Ronaldo", "Bebeto", "Neymar", "Adriano", "Careca"],
  ),
  fut(
    "fut-europa",
    "Estrelas da Europa",
    "🌍",
    ["Neuer", "Oblak", "Maignan", "Onana", "Raya", "Szczesny"],
    ["Saliba", "Bastoni", "Kimmich", "Theo Hernández", "Trent", "Davies", "Araújo"],
    ["Modric", "Ødegaard", "Foden", "Musiala", "Wirtz", "Barella", "Pedri", "Gavi", "Zubimendi"],
    ["Kane", "Salah", "Lewandowski", "Osimhen", "Vlahovic", "Nkunku", "Rafael Leão"],
  ),
  fut(
    "fut-futsal",
    "Futsal / várzea dos sonhos",
    "🥅",
    ["Falcão (goleiro linha)", "Tiago", "Guitta", "Willian", "Zé Filho"],
    ["Rodrigo", "Bateria", "Dieguinho", "Vinícius", "Nem"],
    ["Falcão", "Manoel Tobias", "Ferrão", "Rodrigo", "Pito", "Léo Santana"],
    ["Ferrão", "Neto", "Marquinhos Xavier", "Dyego", "Pedro Batata"],
  ),
  fut(
    "fut-camisa10",
    "Camisa 10 eterna",
    "🔟",
    ["Higuita", "Rogério Ceni", "Chilavert", "Bravo", "Muslera"],
    ["Maicon", "Zanetti", "Lahm", "Sergio Ramos", "Piqué"],
    [
      "Maradona",
      "Riquelme",
      "Totti",
      "Del Piero",
      "Rui Costa",
      "Alex",
      "D'Alessandro",
      "Valderrama",
    ],
    ["Messi", "Cristiano Ronaldo", "Ibrahimovic", "Suárez", "Agüero", "Tevez"],
  ),

  // ===== TEMAS LIVRES =====
  free("marcas", "Marcas famosas", "🏷️", [
    "Apple",
    "Nike",
    "Coca-Cola",
    "Samsung",
    "Adidas",
    "Google",
    "Amazon",
    "Havaianas",
    "Natura",
    "Nestlé",
    "Tesla",
    "Netflix",
    "Lacta",
    "Bauducco",
    "Puma",
    "Sony",
  ]),
  free("filmes", "Filmes", "🎬", [
    "Titanic",
    "Vingadores: Ultimato",
    "O Rei Leão",
    "Interstellar",
    "Coringa",
    "Matrix",
    "Se Beber Não Case",
    "Cidade de Deus",
    "Toy Story",
    "Homem-Aranha",
    "Harry Potter",
    "Velozes e Furiosos",
    "Parasita",
    "Divertida Mente",
    "Shrek",
    "Barbie",
  ]),
  free("series", "Séries", "📺", [
    "Breaking Bad",
    "Game of Thrones",
    "Friends",
    "Stranger Things",
    "The Office",
    "La Casa de Papel",
    "Dark",
    "Chaves",
    "Round 6",
    "Peaky Blinders",
    "Grey's Anatomy",
    "Better Call Saul",
    "Modern Family",
    "Vikings",
  ]),
  free("animes", "Animes", "🌸", [
    "Naruto",
    "One Piece",
    "Attack on Titan",
    "Death Note",
    "Dragon Ball",
    "Jujutsu Kaisen",
    "Demon Slayer",
    "Fullmetal Alchemist",
    "Hunter x Hunter",
    "Cowboy Bebop",
    "Chainsaw Man",
    "Steins;Gate",
    "Your Name",
    "Spy x Family",
  ]),
  free("cantores", "Cantores brasileiros", "🎤", [
    "Anitta",
    "Ivete Sangalo",
    "Caetano Veloso",
    "Marília Mendonça",
    "Gusttavo Lima",
    "Ludmilla",
    "Djavan",
    "Roberto Carlos",
    "Luan Santana",
    "Jorge & Mateus",
    "Alcione",
    "Emicida",
    "Pabllo Vittar",
    "Zé Neto & Cristiano",
  ]),
  free("internacionais", "Artistas internacionais", "🌟", [
    "Beyoncé",
    "Michael Jackson",
    "Taylor Swift",
    "Drake",
    "Adele",
    "Rihanna",
    "Eminem",
    "Bad Bunny",
    "Bruno Mars",
    "Billie Eilish",
    "The Weeknd",
    "Shakira",
    "Ed Sheeran",
    "Lady Gaga",
  ]),
  free("bandas", "Bandas de rock", "🎸", [
    "Queen",
    "Beatles",
    "Nirvana",
    "Linkin Park",
    "Legião Urbana",
    "Charlie Brown Jr.",
    "AC/DC",
    "Guns N' Roses",
    "Coldplay",
    "Red Hot Chili Peppers",
    "Pink Floyd",
    "Skank",
    "Titãs",
    "Metallica",
  ]),
  free("comidas", "Comidas", "🍔", [
    "Pizza",
    "Feijoada",
    "Sushi",
    "Hambúrguer",
    "Lasanha",
    "Açaí",
    "Coxinha",
    "Pastel de feira",
    "Churrasco",
    "Strogonoff",
    "Tapioca",
    "Brigadeiro",
    "Escondidinho",
    "Yakisoba",
  ]),
  free("sobremesas", "Sobremesas", "🍰", [
    "Sorvete de chocolate",
    "Pudim",
    "Brownie",
    "Torta de limão",
    "Petit gateau",
    "Açaí com leite ninho",
    "Bolo de cenoura",
    "Mousse de maracujá",
    "Churros",
    "Cheesecake",
    "Pavê",
    "Milkshake",
  ]),
  free("carros", "Carros", "🚗", [
    "Ferrari",
    "Lamborghini",
    "Porsche 911",
    "Fiat Uno",
    "Civic",
    "Corolla",
    "Mustang",
    "Gol quadrado",
    "Jeep Compass",
    "BMW M3",
    "Tesla Model 3",
    "Kombi",
    "HB20",
    "Range Rover",
  ]),
  free("cidades", "Cidades para morar", "🏙️", [
    "Paris",
    "Tóquio",
    "Nova York",
    "Rio de Janeiro",
    "Lisboa",
    "Barcelona",
    "Florianópolis",
    "Roma",
    "Londres",
    "Buenos Aires",
    "Curitiba",
    "Amsterdã",
    "Seul",
    "Dubai",
  ]),
  free("paises", "Países para viajar", "🌎", [
    "Japão",
    "Itália",
    "França",
    "Brasil",
    "Grécia",
    "Canadá",
    "Portugal",
    "Argentina",
    "Tailândia",
    "Egito",
    "Nova Zelândia",
    "Chile",
    "Espanha",
    "Maldivas",
  ]),
  free("praias", "Praias e destinos", "🏝️", [
    "Fernando de Noronha",
    "Jericoacoara",
    "Maragogi",
    "Ilha Grande",
    "Bombinhas",
    "Porto de Galinhas",
    "Cancún",
    "Bali",
    "Santorini",
    "Arraial do Cabo",
    "Búzios",
    "Morro de São Paulo",
  ]),
  free("animais", "Animais de estimação", "🐶", [
    "Golden retriever",
    "Salsicha",
    "Gato siamês",
    "Poodle",
    "Pug",
    "Border collie",
    "Coelho",
    "Hamster",
    "Calopsita",
    "Gato laranja",
    "Bulldog francês",
    "Shih tzu",
    "Husky",
    "Pinscher",
  ]),
  free("superherois", "Super-heróis", "🦸", [
    "Homem-Aranha",
    "Batman",
    "Superman",
    "Mulher-Maravilha",
    "Homem de Ferro",
    "Thor",
    "Capitão América",
    "Hulk",
    "Flash",
    "Pantera Negra",
    "Doutor Estranho",
    "Deadpool",
    "Wolverine",
    "Viúva Negra",
  ]),
  free("viloes", "Vilões", "😈", [
    "Thanos",
    "Coringa",
    "Darth Vader",
    "Voldemort",
    "Sauron",
    "Freeza",
    "Madara",
    "Cruella",
    "Scar",
    "Hannibal Lecter",
    "Bowser",
    "Pennywise",
  ]),
  free("jogos", "Jogos", "🎮", [
    "Minecraft",
    "GTA V",
    "The Last of Us",
    "FIFA",
    "Free Fire",
    "League of Legends",
    "Zelda",
    "Mario Kart",
    "Elden Ring",
    "Valorant",
    "Among Us",
    "God of War",
    "CS",
    "Stardew Valley",
  ]),
  free("apps", "Aplicativos", "📱", [
    "WhatsApp",
    "Instagram",
    "TikTok",
    "YouTube",
    "Spotify",
    "Uber",
    "iFood",
    "Netflix",
    "Pix",
    "Google Maps",
    "Pinterest",
    "Shopee",
    "Duolingo",
    "Twitter/X",
  ]),
  free("profissoes", "Profissões", "💼", [
    "Médico",
    "Engenheiro",
    "Professor",
    "Programador",
    "Piloto",
    "Chef de cozinha",
    "Advogado",
    "Jogador de futebol",
    "Youtuber",
    "Dentista",
    "Arquiteto",
    "Enfermeiro",
    "Designer",
    "Bombeiro",
  ]),
  free("superpoderes", "Superpoderes", "✨", [
    "Voar",
    "Invisibilidade",
    "Ler mentes",
    "Teletransporte",
    "Parar o tempo",
    "Força infinita",
    "Cura instantânea",
    "Falar com animais",
    "Viajar no tempo",
    "Controlar o clima",
    "Vida eterna",
    "Sorte absoluta",
  ]),
  free("esportes", "Esportes", "🏀", [
    "Futebol",
    "Basquete",
    "Vôlei",
    "MMA",
    "Natação",
    "Tênis",
    "Fórmula 1",
    "Skate",
    "Surfe",
    "Handebol",
    "Ginástica",
    "Boxe",
    "Ciclismo",
    "Atletismo",
  ]),
  free("atletas", "Atletas de outros esportes", "🥇", [
    "Michael Jordan",
    "LeBron James",
    "Ayrton Senna",
    "Lewis Hamilton",
    "Serena Williams",
    "Usain Bolt",
    "Rafael Nadal",
    "Simone Biles",
    "Anderson Silva",
    "Rebeca Andrade",
    "Marta",
    "Giba",
    "Cesar Cielo",
    "Kobe Bryant",
  ]),
  free("youtubers", "Criadores de conteúdo", "🎥", [
    "Whindersson Nunes",
    "Felipe Neto",
    "Casimiro",
    "MrBeast",
    "Rezendeevil",
    "Virginia",
    "Gaules",
    "Enaldinho",
    "Luba",
    "Nilce",
    "Bianca Andrade",
    "Cellbit",
  ]),
  free("desenhos", "Desenhos animados", "📼", [
    "Bob Esponja",
    "Os Simpsons",
    "Pokémon",
    "Turma da Mônica",
    "Scooby-Doo",
    "Tom & Jerry",
    "Os Padrinhos Mágicos",
    "Hora de Aventura",
    "Digimon",
    "Ben 10",
    "Pica-Pau",
    "Rick and Morty",
  ]),
  free("disney", "Personagens Disney/Pixar", "🏰", [
    "Mickey",
    "Simba",
    "Elsa",
    "Woody",
    "Buzz Lightyear",
    "Nemo",
    "Mulan",
    "Aladdin",
    "Rapunzel",
    "Wall-E",
    "Remy",
    "Moana",
    "Stitch",
    "Ariel",
  ]),
  free("doces", "Doces de mercado", "🍬", [
    "Bis",
    "Kinder Bueno",
    "Sonho de Valsa",
    "Trident",
    "Halls",
    "Nutella",
    "Ovomaltine",
    "Ferrero Rocher",
    "Talento",
    "Prestígio",
    "Baton",
    "Diamante Negro",
  ]),
  free("bebidas", "Bebidas", "🥤", [
    "Coca-Cola",
    "Guaraná",
    "Suco de laranja",
    "Café",
    "Chá gelado",
    "Água de coco",
    "Milkshake",
    "Cerveja",
    "Vinho",
    "Energético",
    "Achocolatado",
    "Limonada suíça",
  ]),
  free("mangas", "Mangás / HQs", "📚", [
    "One Piece",
    "Berserk",
    "Naruto",
    "Vagabond",
    "Monster",
    "Batman: Cavaleiro das Trevas",
    "Watchmen",
    "Homem-Aranha: Renove seus Votos",
    "Vinland Saga",
    "Slam Dunk",
    "Tokyo Ghoul",
    "Blame!",
  ]),
  free("tecnologia", "Gadgets e tecnologia", "🔌", [
    "iPhone",
    "PlayStation 5",
    "Nintendo Switch",
    "AirPods",
    "MacBook",
    "Alexa",
    "Kindle",
    "Apple Watch",
    "Drone",
    "GoPro",
    "Xbox",
    "iPad",
    "Caixa JBL",
    "Robô aspirador",
  ]),
  free("materias", "Matérias da escola", "🏫", [
    "Matemática",
    "Português",
    "História",
    "Geografia",
    "Biologia",
    "Física",
    "Química",
    "Educação Física",
    "Artes",
    "Inglês",
    "Filosofia",
    "Sociologia",
  ]),
  free("emojis", "Emojis", "🙂", [
    "😂",
    "❤️",
    "🥺",
    "😎",
    "🔥",
    "💀",
    "🙏",
    "🤡",
    "😍",
    "🤔",
    "😭",
    "👀",
    "✨",
    "🥰",
  ]),
  free("redes", "Redes sociais", "🌐", [
    "Instagram",
    "TikTok",
    "WhatsApp",
    "X (Twitter)",
    "YouTube",
    "Facebook",
    "Threads",
    "Pinterest",
    "LinkedIn",
    "Snapchat",
    "Discord",
    "Twitch",
  ]),
  free("filmesbr", "Filmes brasileiros", "🎞️", [
    "Cidade de Deus",
    "Tropa de Elite",
    "Central do Brasil",
    "Auto da Compadecida",
    "Bacurau",
    "Minha Mãe é uma Peça",
    "Ainda Estou Aqui",
    "Carandiru",
    "O Palhaço",
    "Que Horas Ela Volta?",
    "Nosso Lar",
    "Chico Xavier",
  ]),
  free("novelas", "Novelas", "📼", [
    "Avenida Brasil",
    "Vale Tudo",
    "Roque Santeiro",
    "Senhora do Destino",
    "Pantanal",
    "A Favorita",
    "Cheias de Charme",
    "Império",
    "Chocolate com Pimenta",
    "Malhação",
    "Rebelde",
    "Carrossel",
  ]),
  free("lugares", "Lugares para um date", "💘", [
    "Cinema",
    "Praia ao pôr do sol",
    "Parque de diversões",
    "Restaurante japonês",
    "Piquenique",
    "Show",
    "Sorveteria",
    "Mirante à noite",
    "Boliche",
    "Café aconchegante",
    "Aquário",
    "Feira noturna",
  ]),
  free("historicos", "Personagens históricos", "🏛️", [
    "Albert Einstein",
    "Cleópatra",
    "Napoleão",
    "Leonardo da Vinci",
    "Nelson Mandela",
    "Marie Curie",
    "Santos Dumont",
    "Gandhi",
    "Isaac Newton",
    "Frida Kahlo",
    "Julio César",
    "Machado de Assis",
  ]),
  free("bilionarios", "Empresas e bilionários", "💰", [
    "Elon Musk",
    "Jeff Bezos",
    "Bill Gates",
    "Jorge Paulo Lemann",
    "Steve Jobs",
    "Mark Zuckerberg",
    "Warren Buffett",
    "Luiza Trajano",
    "Petrobras",
    "Vale",
    "Magalu",
    "Ambev",
  ]),
  free("monstros", "Monstros e criaturas", "👹", [
    "Dragão",
    "Godzilla",
    "King Kong",
    "Lobisomem",
    "Vampiro",
    "Zumbi",
    "Kraken",
    "Minotauro",
    "Fênix",
    "Saci",
    "Curupira",
    "Yeti",
  ]),
  free("times", "Times do coração", "🛡️", [
    "Flamengo",
    "Corinthians",
    "Palmeiras",
    "São Paulo",
    "Grêmio",
    "Internacional",
    "Cruzeiro",
    "Atlético-MG",
    "Vasco",
    "Fluminense",
    "Santos",
    "Bahia",
    "Real Madrid",
    "Barcelona",
  ]),
  free("musicas", "Músicas para o carro", "🎶", [
    "Evidências",
    "Bohemian Rhapsody",
    "Deixa Acontecer",
    "Blinding Lights",
    "Envolver",
    "Sweet Child O' Mine",
    "Trem-Bala",
    "Shape of You",
    "Ai Se Eu Te Pego",
    "Tocando em Frente",
    "Vai Malandra",
    "Perfect",
  ]),
];

const USED_KEY = "lel_used_v1";
const BUDGETS = [50, 60, 80, 100, 120, 150, 200, 250];

function readUsed(): string[] {
  try {
    return JSON.parse(localStorage.getItem(USED_KEY) ?? "[]") as string[];
  } catch {
    return [];
  }
}

export function markThemeUsed(id: string) {
  try {
    const used = readUsed();
    const next = [...used, id];
    localStorage.setItem(USED_KEY, JSON.stringify(next.length >= THEMES.length ? [id] : next));
  } catch {
    /* noop */
  }
}

export function pickThemeIndex(): number {
  const used = new Set(readUsed());
  const pool = THEMES.map((t, i) => i).filter((i) => !used.has(THEMES[i].id));
  const list = pool.length ? pool : THEMES.map((_, i) => i);
  return list[Math.floor(Math.random() * list.length)];
}

export function pickBudget(): number {
  return BUDGETS[Math.floor(Math.random() * BUDGETS.length)];
}

/** Sorteia 2 candidatos por slot (10 itens), sem repetir. */
export function draftItems(theme: LeilaoTheme): string[][] {
  const usedItems = new Set<string>();
  return theme.slots.map((_, slot) => {
    const pool = (theme.pools[slot] ?? theme.pools[0]).filter((i) => !usedItems.has(i));
    const shuffled = [...pool].sort(() => Math.random() - 0.5);
    const pair = shuffled.slice(0, 2);
    pair.forEach((i) => usedItems.add(i));
    return pair;
  });
}
