export type PartyMode = "nunca" | "provavel";
export type PartyLevel = "fofo" | "engracado" | "apimentado";

export const LEVELS: { key: PartyLevel; name: string; desc: string }[] = [
  { key: "fofo", name: "Fofo", desc: "romântico e leve" },
  { key: "engracado", name: "Engraçado", desc: "vergonha e risada" },
  { key: "apimentado", name: "Apimentado", desc: "ousado, só pra nós" },
];

// Tudo sobre o casal / o presente — nada sobre relacionamentos anteriores.
export const PROMPTS: Record<PartyMode, Record<PartyLevel, string[]>> = {
  nunca: {
    fofo: [
      "Eu nunca reli nossas mensagens antigas só pra sorrir",
      "Eu nunca dormi pensando em você",
      "Eu nunca guardei um print de algo que você disse",
      "Eu nunca imaginei como vai ser nossa casa",
      "Eu nunca senti saudade minutos depois de a gente se despedir",
      "Eu nunca escolhi uma roupa pensando se você ia gostar",
      "Eu nunca ouvi uma música e lembrei na hora de você",
      "Eu nunca fiquei olhando sua foto por muito tempo",
      "Eu nunca contei pra alguém o quanto gosto de você",
      "Eu nunca pensei em nomes de filhos nossos",
      "Eu nunca chorei de saudade de você",
      "Eu nunca planejei uma surpresa pra você em segredo",
      "Eu nunca sonhei com você",
      "Eu nunca dei um sorriso bobo no meio da rua por causa de uma mensagem sua",
      "Eu nunca imaginei nossa viagem dos sonhos",
      "Eu nunca senti ciúmes bobo de você",
      "Eu nunca fiquei com vergonha de dizer eu te amo primeiro",
      "Eu nunca deixei de dormir pra continuar conversando com você",
      "Eu nunca pensei em como seria nosso casamento",
      "Eu nunca senti borboletas no estômago só de te ver online",
    ],
    engracado: [
      "Eu nunca fingi que entendi algo que você explicou",
      "Eu nunca mandei mensagem pra você e apaguei rapidinho",
      "Eu nunca stalkeei suas fotos antigas até muito lá embaixo",
      "Eu nunca ensaiei um áudio antes de mandar pra você",
      "Eu nunca fingi estar ocupado(a) pra não parecer desesperado(a)",
      "Eu nunca ri sozinho(a) de algo que você falou dias depois",
      "Eu nunca tropecei tentando parecer bonito(a) na sua frente",
      "Eu nunca cantei alto achando que ninguém ouvia",
      "Eu nunca comi algo escondido pra não dividir",
      "Eu nunca esqueci o que ia falar no meio de uma frase com você",
      "Eu nunca mandei mensagem pra pessoa errada",
      "Eu nunca dormi no meio de uma ligação com você",
      "Eu nunca tirei mais de 20 selfies pra mandar uma só",
      "Eu nunca dei um nome engraçado pra você no meu celular",
      "Eu nunca fingi que estava rindo de outra coisa",
      "Eu nunca conversei com um animal como se fosse gente",
      "Eu nunca chorei em desenho animado",
      "Eu nunca fiz careta no espelho treinando expressões",
      "Eu nunca menti sobre já ter assistido um filme",
      "Eu nunca dancei sozinho(a) no quarto",
    ],
    apimentado: [
      "Eu nunca imaginei nosso próximo beijo durante o dia",
      "Eu nunca senti vontade de te agarrar no meio de uma conversa séria",
      "Eu nunca fiquei sem graça com um olhar seu",
      "Eu nunca pensei em você e fiquei vermelho(a)",
      "Eu nunca quis te beijar na frente de todo mundo",
      "Eu nunca reparei demais na sua boca enquanto você falava",
      "Eu nunca escolhi um perfume pensando em você",
      "Eu nunca fiquei arrepiado(a) com um áudio seu",
      "Eu nunca imaginei um encontro só nosso, sem hora pra acabar",
      "Eu nunca quis te mandar uma mensagem ousada e desisti",
      "Eu nunca senti ciúmes de alguém olhando pra você",
      "Eu nunca fiquei pensando em um abraço seu a noite inteira",
      "Eu nunca quis ficar grudado(a) em você o dia todo",
      "Eu nunca achei você irresistível com uma roupa específica",
      "Eu nunca pensei num beijo no pescoço",
      "Eu nunca tive vontade de te puxar pra perto sem aviso",
      "Eu nunca fiquei nervoso(a) por estar perto demais de você",
      "Eu nunca sonhei com um beijo nosso",
      "Eu nunca quis te provocar só pra ver sua reação",
      "Eu nunca mordi o lábio olhando pra você",
    ],
  },
  provavel: {
    fofo: [
      "Quem é mais provável de chorar no nosso casamento?",
      "Quem é mais provável de dizer eu te amo primeiro no dia?",
      "Quem é mais provável de planejar um encontro surpresa?",
      "Quem é mais provável de guardar cada presente?",
      "Quem é mais provável de sentir saudade primeiro?",
      "Quem é mais provável de escrever uma carta de amor?",
      "Quem é mais provável de querer um pet primeiro?",
      "Quem é mais provável de lembrar de todas as datas?",
      "Quem é mais provável de fazer café da manhã na cama?",
      "Quem é mais provável de pedir desculpa primeiro?",
      "Quem é mais provável de dormir abraçado(a) a noite toda?",
      "Quem é mais provável de chorar vendo filme romântico?",
      "Quem é mais provável de mandar bom dia primeiro?",
      "Quem é mais provável de cuidar do outro quando está doente?",
      "Quem é mais provável de dar o último pedaço da comida?",
      "Quem é mais provável de montar um álbum nosso?",
      "Quem é mais provável de fazer uma playlist pro outro?",
      "Quem é mais provável de pedir em casamento?",
      "Quem é mais provável de ficar bobo(a) olhando o outro dormir?",
      "Quem é mais provável de ligar só pra ouvir a voz?",
    ],
    engracado: [
      "Quem é mais provável de se perder num shopping?",
      "Quem é mais provável de queimar a comida?",
      "Quem é mais provável de rir num momento sério?",
      "Quem é mais provável de esquecer onde deixou o celular estando com ele na mão?",
      "Quem é mais provável de dormir no cinema?",
      "Quem é mais provável de ficar emburrado(a) com fome?",
      "Quem é mais provável de cair da cadeira?",
      "Quem é mais provável de demorar mais pra se arrumar?",
      "Quem é mais provável de falar dormindo?",
      "Quem é mais provável de virar meme?",
      "Quem é mais provável de comer o lanche do outro?",
      "Quem é mais provável de fazer drama por um machucadinho?",
      "Quem é mais provável de ganhar uma discussão?",
      "Quem é mais provável de ter medo de barata?",
      "Quem é mais provável de roubar a coberta?",
      "Quem é mais provável de cantar errado a música inteira?",
      "Quem é mais provável de desistir de um exercício no meio?",
      "Quem é mais provável de comprar algo inútil?",
      "Quem é mais provável de chegar atrasado(a)?",
      "Quem é mais provável de sobreviver a um apocalipse zumbi?",
    ],
    apimentado: [
      "Quem é mais provável de roubar um beijo do nada?",
      "Quem é mais provável de provocar o outro de propósito?",
      "Quem é mais provável de ficar com ciúmes primeiro?",
      "Quem é mais provável de mandar uma mensagem ousada?",
      "Quem é mais provável de não resistir a um olhar?",
      "Quem é mais provável de puxar o outro pra dançar colado?",
      "Quem é mais provável de ficar vermelho(a) primeiro?",
      "Quem é mais provável de pedir mais um beijo?",
      "Quem é mais provável de sussurrar algo no ouvido?",
      "Quem é mais provável de ficar sem graça com um elogio?",
      "Quem é mais provável de planejar um encontro romântico à luz de velas?",
      "Quem é mais provável de dar um abraço por trás?",
      "Quem é mais provável de perder a concentração olhando o outro?",
      "Quem é mais provável de fazer uma declaração ousada?",
      "Quem é mais provável de não querer soltar no abraço?",
      "Quem é mais provável de beijar no meio de uma briga boba?",
      "Quem é mais provável de flertar mesmo depois de anos?",
      "Quem é mais provável de pedir carinho primeiro?",
      "Quem é mais provável de morder o lábio sem perceber?",
      "Quem é mais provável de ganhar no jogo da sedução?",
    ],
  },
};
