// Nível "Safado" — quente e provocante, só sobre os dois, sem nada gráfico.
export const SAFADO_NUNCA = [
  "Eu nunca fiquei com vontade de te tirar a roupa só com o olhar",
  "Eu nunca imaginei a gente se pegando num lugar público",
  "Eu nunca pensei em você de um jeito bem safado no meio do dia",
  "Eu nunca quis te beijar no pescoço até você arrepiar",
  "Eu nunca fiquei com tesão só lendo uma mensagem sua",
  "Eu nunca imaginei você usando só uma camiseta minha",
  "Eu nunca pensei em te acordar com beijos bem safados",
  "Eu nunca quis te prensar na parede pra te beijar",
  "Eu nunca tive um sonho quente com você",
  "Eu nunca fiquei imaginando o que faria com você numa banheira",
  "Eu nunca quis morder sua boca de propósito",
  "Eu nunca imaginei a gente trancado num quarto de hotel o fim de semana todo",
  "Eu nunca pensei numa lingerie/cueca que queria te ver usando",
  "Eu nunca fiquei louco(a) pra sussurrar uma safadeza no seu ouvido",
  "Eu nunca quis te provocar por baixo da mesa",
  "Eu nunca imaginei um banho a dois com você",
  "Eu nunca pensei em te vendar e te deixar adivinhando",
  "Eu nunca senti vontade de te agarrar assim que te vi",
  "Eu nunca fiquei olhando seu corpo quando você não tava percebendo",
  "Eu nunca quis fazer uma massagem em você que terminasse em outra coisa",
  "Eu nunca imaginei a gente se pegando no carro",
  "Eu nunca pensei em mandar uma foto bem provocante pra você",
  "Eu nunca quis tirar sua roupa bem devagar",
  "Eu nunca tive uma fantasia com você que nunca contei",
  "Eu nunca fiquei com vontade de te morder inteiro(a)",
  "Eu nunca imaginei a gente numa noite inteira sem dormir, e não era conversando",
  "Eu nunca pensei em te deixar marcas de beijo",
  "Eu nunca quis te dominar um pouquinho",
  "Eu nunca quis ser dominado(a) por você",
  "Eu nunca fiquei excitado(a) só de lembrar do seu cheiro",
  "Eu nunca pensei num lugar ousado onde queria te beijar",
  "Eu nunca imaginei a gente dançando colado até perder o controle",
  "Eu nunca quis te ouvir gemendo meu nome",
  "Eu nunca pensei em brincar com gelo em você",
  "Eu nunca quis passar chocolate em você só pra tirar com a boca",
];
export const SAFADO_PROVAVEL = [
  "Quem é mais provável de começar a provocação primeiro?",
  "Quem é mais provável de mandar uma mensagem safada do nada?",
  "Quem é mais provável de tirar a roupa do outro primeiro?",
  "Quem é mais provável de propor uma pegação em lugar proibido?",
  "Quem é mais provável de ficar com tesão primeiro?",
  "Quem é mais provável de pedir pra repetir a noite?",
  "Quem é mais provável de comprar uma lingerie/cueca pra provocar?",
  "Quem é mais provável de sussurrar uma safadeza em público?",
  "Quem é mais provável de deixar marca de chupão?",
  "Quem é mais provável de puxar o outro pro banho?",
  "Quem é mais provável de ter a fantasia mais ousada?",
  "Quem é mais provável de não aguentar esperar chegar em casa?",
  "Quem é mais provável de provocar por baixo da mesa?",
  "Quem é mais provável de mandar a foto mais ousada?",
  "Quem é mais provável de vendar o outro?",
  "Quem é mais provável de ser mais barulhento(a)?",
  "Quem é mais provável de morder durante o beijo?",
  "Quem é mais provável de acordar o outro com segundas intenções?",
  "Quem é mais provável de comandar a noite?",
  "Quem é mais provável de pedir massagem querendo outra coisa?",
  "Quem é mais provável de se pegar no carro?",
  "Quem é mais provável de rasgar a roupa na pressa?",
  "Quem é mais provável de ficar vermelho(a) com uma safadeza?",
  "Quem é mais provável de sugerir algo novo na cama?",
  "Quem é mais provável de ficar pelado(a) primeiro?",
  "Quem é mais provável de provocar sabendo que não dá pra fazer nada?",
  "Quem é mais provável de esquecer a vergonha de vez?",
  "Quem é mais provável de pedir \"de novo\"?",
  "Quem é mais provável de fazer um strip-tease?",
  "Quem é mais provável de ligar só pra falar safadeza?",
];

SAFADO_NUNCA.push(
  "Eu nunca fiquei pensando em você no banho",
  "Eu nunca quis te beijar até a gente perder o fôlego",
  "Eu nunca imaginei você me provocando por mensagem no meio da aula/trabalho",
  "Eu nunca quis te puxar pelo cós da calça",
  "Eu nunca pensei em te dar um beijo na nuca de surpresa",
  "Eu nunca fiquei com vontade de dormir agarradinho sem roupa",
  "Eu nunca quis te ver dançando só pra mim",
  "Eu nunca imaginei uma noite de motel com você",
  "Eu nunca quis fazer um date que terminasse no quarto",
  "Eu nunca pensei em você usando uma fantasia sexy",
  "Eu nunca quis te deixar sem graça com uma frase safada",
  "Eu nunca quis passar a mão em você no cinema",
  "Eu nunca imaginei a gente na praia de noite, sozinhos",
  "Eu nunca quis te morder a orelha",
  "Eu nunca fiquei arrepiado(a) com sua voz no meu ouvido",
  "Eu nunca quis te dar um banho de beijos",
  "Eu nunca pensei em fazer um jogo de strip com você",
  "Eu nunca quis te segurar pelo cabelo durante o beijo",
  "Eu nunca imaginei a gente numa piscina à noite",
  "Eu nunca quis te mandar um áudio sussurrando",
  "Eu nunca quis que você me amarrasse com uma gravata",
  "Eu nunca pensei em te dar uma massagem com óleo",
  "Eu nunca fiquei com vontade de te beijar em cada pedacinho",
  "Eu nunca imaginei a gente numa cabana com lareira e pouca roupa",
  "Eu nunca quis passar o dia inteiro na cama com você",
  "Eu nunca quis te ver só de toalha saindo do banho",
  "Eu nunca pensei em te provocar só de olhar",
  "Eu nunca quis fazer você perder a cabeça",
  "Eu nunca imaginei a gente na cozinha, e não era cozinhando",
  "Eu nunca quis te dar um chupão escondido",
  "Eu nunca pensei em um apelido safado pra você",
  "Eu nunca quis que você me acordasse no meio da noite com segundas intenções",
  "Eu nunca imaginei você de lingerie/cueca vermelha",
  "Eu nunca quis tirar foto nossa bem ousada",
  "Eu nunca fiquei com ciúme da sua roupa por estar te abraçando o dia todo",
  "Eu nunca quis te beijar no elevador",
  "Eu nunca imaginei uma noite inteira de provocação sem poder tocar",
  "Eu nunca quis brincar de vendar e adivinhar onde é o beijo",
  "Eu nunca quis te ouvir pedindo mais",
  "Eu nunca pensei em fazer uma noite temática só nossa",
  "Eu nunca quis te deixar com as pernas bambas",
  "Eu nunca imaginei a gente embaixo do chuveiro quente",
  "Eu nunca quis que você me provocasse em público e eu não pudesse fazer nada",
  "Eu nunca quis te encostar na porta assim que você chegasse",
  "Eu nunca fiquei vermelho(a) lembrando de uma noite nossa",
  "Eu nunca quis escrever uma lista de coisas safadas pra fazer com você",
  "Eu nunca imaginei você sussurrando o que quer fazer comigo",
  "Eu nunca quis te beijar devagar até você implorar",
  "Eu nunca quis te mandar mensagem só com 'tô pensando em você daquele jeito'",
  "Eu nunca imaginei a gente se pegando numa barraca de camping",
);
SAFADO_PROVAVEL.push(
  "Quem é mais provável de mandar nude primeiro?",
  "Quem é mais provável de pedir mais um beijo depois do 'último'?",
  "Quem é mais provável de não conseguir manter as mãos quietas?",
  "Quem é mais provável de propor um banho juntos?",
  "Quem é mais provável de ficar com vergonha depois de uma safadeza?",
  "Quem é mais provável de comprar algo pra apimentar a relação?",
  "Quem é mais provável de provocar no cinema?",
  "Quem é mais provável de sussurrar o que quer no ouvido?",
  "Quem é mais provável de dar o primeiro chupão?",
  "Quem é mais provável de sugerir motel?",
  "Quem é mais provável de ficar arrepiado(a) mais fácil?",
  "Quem é mais provável de beijar até perder o fôlego?",
  "Quem é mais provável de esquecer a hora na cama?",
  "Quem é mais provável de fazer dança sensual?",
  "Quem é mais provável de pedir pra apagar a luz?",
  "Quem é mais provável de pedir pra deixar a luz acesa?",
  "Quem é mais provável de amarrar o outro com uma gravata?",
  "Quem é mais provável de morder de leve?",
  "Quem é mais provável de se arrumar só pra provocar?",
  "Quem é mais provável de mandar áudio safado?",
  "Quem é mais provável de puxar pela roupa pra beijar?",
  "Quem é mais provável de propor um jogo de strip?",
  "Quem é mais provável de ficar sem roupa mais rápido?",
  "Quem é mais provável de aguentar menos tempo na provocação?",
  "Quem é mais provável de agarrar assim que abrir a porta?",
  "Quem é mais provável de ter mais imaginação safada?",
  "Quem é mais provável de fazer massagem com segundas intenções?",
  "Quem é mais provável de deixar o outro louco só com beijo?",
  "Quem é mais provável de querer de manhã?",
  "Quem é mais provável de querer de madrugada?",
  "Quem é mais provável de escolher a lingerie/cueca do outro?",
  "Quem é mais provável de propor algo bem ousado na viagem?",
  "Quem é mais provável de se pegar no elevador?",
  "Quem é mais provável de pedir pra repetir na mesma noite?",
  "Quem é mais provável de ficar mais safado(a) com o tempo?",
  "Quem é mais provável de provocar por chamada de vídeo?",
  "Quem é mais provável de beijar o pescoço sem avisar?",
  "Quem é mais provável de vendar o outro pra surpresa?",
  "Quem é mais provável de corar com um elogio safado?",
  "Quem é mais provável de criar uma noite temática?",
  "Quem é mais provável de tomar a iniciativa hoje?",
  "Quem é mais provável de pedir carinho e acabar em outra coisa?",
  "Quem é mais provável de usar só uma camiseta do outro?",
  "Quem é mais provável de não deixar o outro dormir?",
  "Quem é mais provável de falar a coisa mais safada desse jogo?",
);
