import { SAFADO_NUNCA, SAFADO_PROVAVEL } from "./embrazaSafado";
export type PartyMode = "nunca" | "provavel";
export type PartyLevel = "fofo" | "engracado" | "apimentado" | "safado";

export const LEVELS: { key: PartyLevel; name: string; desc: string }[] = [
  { key: "fofo", name: "Fofo", desc: "romântico e leve" },
  { key: "engracado", name: "Engraçado", desc: "vergonha e risada" },
  { key: "apimentado", name: "Apimentado", desc: "ousado, só pra nós" },
  { key: "safado", name: "Safado", desc: "quente de verdade" },
];

// Tudo sobre o casal no presente — nada de ex, passado ou ciúmes.
export const PROMPTS: Record<PartyMode, Record<PartyLevel, string[]>> = {
  nunca: {
    fofo: [
      "Eu nunca reli nossas mensagens antigas só pra sorrir",
      "Eu nunca dormi pensando em você",
      "Eu nunca guardei um print de algo que você disse",
      "Eu nunca imaginei como vai ser nossa casa",
      "Eu nunca senti saudade minutos depois de a gente se despedir",
      "Eu nunca escolhi uma roupa pensando se você ia gostar",
      "Eu nunca ouvi uma música e lembrei na hora de você",
      "Eu nunca fiquei olhando sua foto por muito tempo",
      "Eu nunca contei pra alguém o quanto gosto de você",
      "Eu nunca pensei em nomes de filhos nossos",
      "Eu nunca chorei de saudade de você",
      "Eu nunca planejei uma surpresa pra você em segredo",
      "Eu nunca sonhei com você",
      "Eu nunca dei um sorriso bobo no meio da rua por causa de uma mensagem sua",
      "Eu nunca imaginei nossa viagem dos sonhos",
      "Eu nunca fiquei com vergonha de dizer eu te amo primeiro",
      "Eu nunca deixei de dormir pra continuar conversando com você",
      "Eu nunca pensei em como seria nosso casamento",
      "Eu nunca senti borboletas no estômago só de te ver online",
      "Eu nunca preparei um café da manhã na cama para você.",
      "Eu nunca escondi um bilhetinho carinhoso na sua mochila.",
      "Eu nunca desenhei um coração na espuma do seu café.",
      "Eu nunca coloquei um alarme só para te desejar um dia lindo.",
      "Eu nunca dividi um guarda-chuva com você bem juntinho.",
      "Eu nunca abracei sua blusa para matar a saudade.",
      "Eu nunca dormi sorrindo depois do seu boa-noite.",
      "Eu nunca marquei no calendário um dia especial nosso.",
      "Eu nunca transformei uma ida ao mercado em um passeio romântico.",
      "Eu nunca fiquei na varanda com você até o céu mudar de cor.",
      "Eu nunca fiz brigadeiro só para dividir a panela com você.",
      "Eu nunca montei uma pizza em formato de coração.",
      "Eu nunca escrevi seu nome na cobertura de um bolo.",
      "Eu nunca deixei meu sorvete derreter enquanto conversava com você.",
      "Eu nunca queimei uma torrada tentando caprichar no seu café.",
      "Eu nunca inventei uma receita e dei a ela o nosso nome.",
      "Eu nunca organizei um piquenique com suas comidas favoritas.",
      "Eu nunca assei biscoitos com mensagens fofas para você.",
      "Eu nunca deixei a última batatinha para você.",
      "Eu nunca fiz chocolate quente para uma noite fria a dois.",
      "Eu nunca arrumei a mala imaginando nossas aventuras.",
      "Eu nunca escrevi nossas iniciais na areia da praia.",
      "Eu nunca acampei com você para contar estrelas.",
      "Eu nunca fechei os olhos e apontei no mapa nossa próxima viagem.",
      "Eu nunca explorei uma cidade de mãos dadas com você.",
      "Eu nunca imaginei uma viagem de trem com sua cabeça no meu ombro.",
      "Eu nunca sonhei em ver a neve numa montanha com você.",
      "Eu nunca escolhi uma pousada só pela vista romântica.",
      "Eu nunca acordei bem cedo para ver o nascer do sol com você.",
      "Eu nunca montei um roteiro de viagem cheio de paradas para comer.",
      "Eu nunca desenhei uma casa com um jardim para nós.",
      "Eu nunca dei nome a uma plantinha que cuidaríamos juntos.",
      "Eu nunca imaginei uma rede grande o bastante para nós dois.",
      "Eu nunca planejei um cantinho de leitura para a gente.",
      "Eu nunca dancei com você enquanto lavávamos a louça.",
      "Eu nunca fiz uma fortaleza de almofadas para nosso encontro.",
      "Eu nunca escolhi mentalmente as cores da nossa futura sala.",
      "Eu nunca sonhei com uma hortinha para temperar nossos almoços.",
      "Eu nunca imaginei um domingo de preguiça na nossa própria casa.",
      "Eu nunca quis encher uma parede com fotos dos nossos momentos.",
      "Eu nunca chorei num filme segurando sua mão.",
      "Eu nunca esperei por você para começar uma série.",
      "Eu nunca dublei uma cena de desenho só para te fazer rir.",
      "Eu nunca fiz pipoca doce e salgada para agradar nós dois.",
      "Eu nunca montei uma playlist que contasse nossa história.",
      "Eu nunca cantei baixinho para você pegar no sono.",
      "Eu nunca dancei agarradinho com você sem música.",
      "Eu nunca guardei um ingresso de show como lembrança nossa.",
      "Eu nunca escrevi uma letra de música pensando em você.",
      "Eu nunca tentei aprender um instrumento para te fazer uma serenata.",
      "Eu nunca coloquei uma foto nossa como papel de parede.",
      "Eu nunca criei uma figurinha com uma careta nossa.",
      "Eu nunca inventei uma combinação de emojis só nossa.",
      "Eu nunca programei uma mensagem fofa para você receber ao acordar.",
      "Eu nunca construí uma casinha para nós num jogo.",
      "Eu nunca combinei meu avatar com o seu.",
      "Eu nunca fiz uma chamada de vídeo só para jantar com você.",
      "Eu nunca organizei nossas fotos em pastas com nomes engraçados.",
      "Eu nunca levei um carregador extra pensando em salvar seu passeio.",
      "Eu nunca mandei um áudio de dez segundos só com beijinhos.",
      "Eu nunca diminuí o ritmo da corrida para acompanhar você.",
      "Eu nunca planejei um passeio de bicicleta com pausa para um abraço.",
      "Eu nunca comemorei um gol te dando um abraço apertado.",
      "Eu nunca fiz alongamento com você ao acordar.",
      "Eu nunca fiz uma trilha com você até uma cachoeira.",
      "Eu nunca tentei andar de patins segurando sua mão.",
      "Eu nunca apostei uma corrida na piscina valendo um cafuné.",
      "Eu nunca formei dupla com você num jogo de vôlei.",
      "Eu nunca fiz um cartaz fofo para torcer por você.",
      "Eu nunca tentei fazer ioga em dupla sem cair na risada.",
      "Eu nunca organizei uma festa só para celebrar uma conquista sua.",
      "Eu nunca fiz uma contagem regressiva para o seu aniversário.",
      "Eu nunca imaginei uma fantasia combinando com a sua.",
      "Eu nunca enchi um quarto de balões com recadinhos para você.",
      "Eu nunca dancei quadrilha com você numa festa junina.",
      "Eu nunca escolhi um dueto romântico para cantarmos no karaokê.",
      "Eu nunca fiquei tirando confetes do seu cabelo depois de uma festa.",
      "Eu nunca fiz um presente à mão pensando em cada detalhe seu.",
      "Eu nunca inventei um feriado nosso para passar o dia juntinho.",
      "Eu nunca fiz um enfeite de Natal com nossas iniciais.",
      "Eu nunca imaginei o nome de um cachorrinho nosso.",
      "Eu nunca quis adotar um gatinho que dormisse entre nossos pés.",
      "Eu nunca planejei um dia de voluntariado com você num abrigo animal.",
      "Eu nunca acordei com você para ouvir os passarinhos.",
      "Eu nunca comparei nossa preguiça de domingo à de uma tartaruguinha.",
      "Eu nunca contei um sonho engraçado só para ouvir sua risada.",
      "Eu nunca pedi mais aventuras nossas ao ver uma estrela cadente.",
      "Eu nunca montei uma cápsula do tempo com lembranças nossas.",
      "Eu nunca fiz uma lista de pequenas coisas que quero aprender com você.",
      "Eu nunca imaginei nós dois velhinhos dividindo uma coberta.",
    ],
    engracado: [
      "Eu nunca fingi que entendi algo que você explicou",
      "Eu nunca mandei mensagem pra você e apaguei rapidinho",
      "Eu nunca ensaiei um áudio antes de mandar pra você",
      "Eu nunca fingi estar ocupado(a) pra não parecer desesperado(a)",
      "Eu nunca ri sozinho(a) de algo que você falou dias depois",
      "Eu nunca tropecei tentando parecer bonito(a) na sua frente",
      "Eu nunca cantei alto achando que ninguém ouvia",
      "Eu nunca comi algo escondido pra não dividir",
      "Eu nunca esqueci o que ia falar no meio de uma frase com você",
      "Eu nunca dormi no meio de uma ligação com você",
      "Eu nunca tirei mais de 20 selfies pra mandar uma só",
      "Eu nunca dei um nome engraçado pra você no meu celular",
      "Eu nunca fingi que estava rindo de outra coisa",
      "Eu nunca conversei com um animal como se fosse gente",
      "Eu nunca chorei em desenho animado",
      "Eu nunca fiz careta no espelho treinando expressões",
      "Eu nunca menti sobre já ter assistido um filme",
      "Eu nunca dancei sozinho(a) no quarto",
      "Eu nunca negociei mais cinco minutos com o despertador como se ele fosse meu chefe.",
      "Eu nunca procurei os óculos enquanto eles estavam no meu rosto.",
      "Eu nunca tomei café e continuei com a disposição de uma batata.",
      "Eu nunca saí com a roupa do avesso e chamei isso de estilo.",
      "Eu nunca entrei num cômodo e esqueci minha missão principal.",
      "Eu nunca esqueci a toalha e fiz uma operação de resgate pingando pela casa.",
      "Eu nunca falei bom dia quando já estava quase escurecendo.",
      "Eu nunca derrubei pasta de dente na roupa segundos antes de sair.",
      "Eu nunca tentei abrir a porta de casa com o cartão do ônibus.",
      "Eu nunca ri sozinho na rua e fingi que estava ouvindo um áudio.",
      "Eu nunca queimei a língua por falta de paciência com uma pizza.",
      "Eu nunca comi o ingrediente antes de terminar a receita.",
      "Eu nunca salguei a comida como se estivesse conservando peixe por cem anos.",
      "Eu nunca pedi comida saudável e completei o pedido com três sobremesas.",
      "Eu nunca derrubei molho na roupa durante a primeira garfada.",
      "Eu nunca tentei virar panqueca no ar e alimentei o chão.",
      "Eu nunca fiz um bolo que poderia servir de tijolo.",
      "Eu nunca abri a geladeira cinco vezes esperando aparecer uma novidade.",
      "Eu nunca escondi um chocolate tão bem que perdi para mim mesmo.",
      "Eu nunca mordi um pastel e fui atacado pelo recheio quente.",
      "Eu nunca levei roupa para quinze dias numa viagem de fim de semana.",
      "Eu nunca tirei uma foto turística com o dedo cobrindo a paisagem.",
      "Eu nunca segui o GPS e terminei encarando um portão fechado.",
      "Eu nunca dormi numa viagem e acordei sem saber em qual dimensão estava.",
      "Eu nunca achei que a mala cabia e precisei sentar nela para fechar.",
      "Eu nunca fui à praia e trouxe mais areia que lembranças.",
      "Eu nunca ensaiei uma frase em outro idioma e travei na primeira palavra.",
      "Eu nunca confundi o andar do hotel e desfilei perdido pelo corredor.",
      "Eu nunca esqueci o protetor numa faixa e ganhei uma tatuagem de sol.",
      "Eu nunca planejei ver o nascer do sol e acordei na hora do almoço.",
      "Eu nunca planejei uma casa enorme sem ter dinheiro nem para o tapete.",
      "Eu nunca escolhi nome para um robô aspirador que ainda nem comprei.",
      "Eu nunca montei um móvel e terminei com peças extras e muita fé.",
      "Eu nunca lavei uma roupa branca e inaugurei uma coleção rosa.",
      "Eu nunca tentei dobrar lençol de elástico e aceitei uma bola de tecido.",
      "Eu nunca matei uma planta que supostamente era impossível de matar.",
      "Eu nunca limpei a casa escondendo tudo dentro de um armário.",
      "Eu nunca tratei uma barata como se fosse um dragão medieval.",
      "Eu nunca fiz orçamento do futuro e esqueci que comida custa dinheiro.",
      "Eu nunca imaginei minha aposentadoria durante uma tarefa de cinco minutos.",
      "Eu nunca dormi no filme que insisti muito para assistir.",
      "Eu nunca dei um grito num filme e me assustei com o meu próprio grito.",
      "Eu nunca tentei adivinhar o final de um filme e errei até o gênero.",
      "Eu nunca chorei numa animação e culpei o ar-condicionado.",
      "Eu nunca cantei a letra errada com confiança de artista principal.",
      "Eu nunca usei uma escova como microfone e agradeci aos meus fãs.",
      "Eu nunca inventei uma coreografia que meu joelho não aprovou.",
      "Eu nunca coloquei uma música triste só para lavar a louça com emoção.",
      "Eu nunca fiquei com um jingle na cabeça por tempo suficiente para cobrar aluguel.",
      "Eu nunca tentei imitar um cantor e produzi um barulho de chaleira.",
      "Eu nunca ensaiei uma discussão com o shampoo e ainda perdi o argumento.",
      "Eu nunca contei degraus e precisei recomeçar porque me distraí.",
      "Eu nunca guardei uma caixa vazia porque ela parecia importante.",
      "Eu nunca apertei o botão do elevador várias vezes para demonstrar urgência.",
      "Eu nunca usei a cadeira como guarda-roupa até ela desaparecer.",
      "Eu nunca sonhei que estava trabalhando e acordei querendo hora extra.",
      "Eu nunca acordei tentando continuar uma conversa que só existiu no sonho.",
      "Eu nunca sonhei que voava e acordei enrolado no lençol.",
      "Eu nunca fiz uma lista de tarefas e coloquei algo já feito só para riscar.",
      "Eu nunca adiei tanto uma tarefa que precisei tirar a poeira dela.",
      "Eu nunca mandei um áudio e descobri que gravei só a minha respiração.",
      "Eu nunca briguei com o corretor automático e perdi em público.",
      "Eu nunca procurei meu celular usando a lanterna do próprio celular.",
      "Eu nunca apareci numa reunião on-line com filtro sem saber tirar.",
      "Eu nunca falei por um minuto inteiro com o microfone desligado.",
      "Eu nunca dei um nome dramático para a rede Wi-Fi.",
      "Eu nunca aceitei os termos como quem assina um pacto sem ler.",
      "Eu nunca tirei cinquenta fotos iguais e não gostei de nenhuma.",
      "Eu nunca pedi ajuda ao assistente virtual e terminei discutindo com ele.",
      "Eu nunca esqueci uma senha logo depois de criar uma senha inesquecível.",
      "Eu nunca fui treinar e cansei durante o aquecimento.",
      "Eu nunca comemorei um gol e descobri que era replay.",
      "Eu nunca errei a bola e acertei uma pose de dança.",
      "Eu nunca comprei roupa de academia para praticar descanso.",
      "Eu nunca tentei fazer ioga e fiquei preso numa posição sem dignidade.",
      "Eu nunca dancei numa festa como se estivesse espantando mosquitos.",
      "Eu nunca comecei o parabéns num tom impossível de sustentar.",
      "Eu nunca estourei uma bexiga e pedi desculpas para ela.",
      "Eu nunca saí de uma festa com glitter em lugares inexplicáveis.",
      "Eu nunca calculei quantos salgadinhos cabiam num guardanapo e desafiei a física.",
      "Eu nunca pedi licença para um cachorro passar.",
      "Eu nunca dei voz ao meu animal e criei uma personalidade insuportável.",
      "Eu nunca perdi meu lugar no sofá para um bicho dez vezes menor.",
      "Eu nunca tentei fotografar um gato e registrei só um borrão de desprezo.",
      "Eu nunca conversei com um passarinho e levei um silêncio constrangedor.",
      "Eu nunca tomei um susto com uma sacola achando que era um animal.",
      "Eu nunca apertei um brinquedo na loja e ele anunciou minha presença ao bairro.",
      "Eu nunca empurrei uma porta que tinha PUXE escrito bem na minha frente.",
      "Eu nunca acenei para alguém que estava dando tchau para a pessoa atrás de mim.",
      "Eu nunca fui jogar o lixo fora e quase descartei a chave junto.",
    ],
    safado: SAFADO_NUNCA,
    apimentado: [
      "Eu nunca imaginei nosso próximo beijo durante o dia",
      "Eu nunca senti vontade de te agarrar no meio de uma conversa séria",
      "Eu nunca fiquei sem graça com um olhar seu",
      "Eu nunca pensei em você e fiquei vermelho(a)",
      "Eu nunca quis te beijar na frente de todo mundo",
      "Eu nunca reparei demais na sua boca enquanto você falava",
      "Eu nunca escolhi um perfume pensando em você",
      "Eu nunca fiquei arrepiado(a) com um áudio seu",
      "Eu nunca imaginei um encontro só nosso, sem hora pra acabar",
      "Eu nunca quis te mandar uma mensagem ousada e desisti",
      "Eu nunca fiquei pensando em um abraço seu a noite inteira",
      "Eu nunca quis ficar grudado(a) em você o dia todo",
      "Eu nunca achei você irresistível com uma roupa específica",
      "Eu nunca pensei num beijo no pescoço",
      "Eu nunca tive vontade de te puxar pra perto sem aviso",
      "Eu nunca fiquei nervoso(a) por estar perto demais de você",
      "Eu nunca sonhei com um beijo nosso",
      "Eu nunca quis te provocar só pra ver sua reação",
      "Eu nunca mordi o lábio olhando pra você",
      "Eu nunca troquei o despertador por mais cinco minutos de abraço.",
      "Eu nunca inventei uma tarefa só para ficar por perto.",
      "Eu nunca transformei a faxina em competição valendo um beijo.",
      "Eu nunca usei uma roupa só para provocar você.",
      "Eu nunca deixei um bilhete ousado no meio da sua rotina.",
      "Eu nunca prolonguei uma despedida até perder a noção da hora.",
      "Eu nunca fiz charme para escapar de lavar a louça.",
      "Eu nunca roubei seu lado da cama e ainda pedi carinho.",
      "Eu nunca comecei o dia sugerindo uma pequena loucura a dois.",
      "Eu nunca me atrasei porque o abraço estava bom demais.",
      "Eu nunca ofereci a última mordida esperando uma recompensa.",
      "Eu nunca preparei um jantar com mais intenção que habilidade.",
      "Eu nunca comi sobremesa antes do prato principal.",
      "Eu nunca desafiei você a provar algo de olhos fechados.",
      "Eu nunca fiz uma receita que parecia mais fácil no vídeo.",
      "Eu nunca escolhi uma comida só porque dava para dividir.",
      "Eu nunca usei o jantar como desculpa para um encontro caprichado.",
      "Eu nunca comi direto da panela durante uma madrugada a dois.",
      "Eu nunca montei um piquenique no chão da sala.",
      "Eu nunca apostei um café da manhã na cama numa disputa boba.",
      "Eu nunca quis comprar uma passagem sem planejar mais nada.",
      "Eu nunca imaginei nós dois numa cabana sem pressa de voltar.",
      "Eu nunca arrumei a mala pensando nos nossos encontros.",
      "Eu nunca sugeri pegar a estrada só para ver onde daria.",
      "Eu nunca quis ver o nascer do sol depois de uma noite conversando.",
      "Eu nunca escolhi uma hospedagem por causa da banheira.",
      "Eu nunca sonhei com uma viagem em que o roteiro fosse você.",
      "Eu nunca entrei no mar de roupa por puro impulso.",
      "Eu nunca quis dançar com você numa rua de outra cidade.",
      "Eu nunca trouxe uma lembrança de viagem que não cabia na mala.",
      "Eu nunca imaginei como seria dividir o mesmo endereço.",
      "Eu nunca planejei uma casa com espaço para nossas manias.",
      "Eu nunca escolhi mentalmente o sofá das nossas maratonas.",
      "Eu nunca quis uma cozinha grande só para cozinhar com você.",
      "Eu nunca pensei em criar uma tradição só nossa.",
      "Eu nunca imaginei nossa vida daqui a vinte anos.",
      "Eu nunca sonhei com uma varanda para namorar sem relógio.",
      "Eu nunca ensaiei um pedido importante diante do espelho.",
      "Eu nunca quis pintar uma parede de uma cor absurda.",
      "Eu nunca guardei dinheiro pensando numa aventura a dois.",
      "Eu nunca escolhi um filme sabendo que ia prestar atenção em você.",
      "Eu nunca pausei uma série para exigir um beijo.",
      "Eu nunca chorei num filme e culpei o cansaço.",
      "Eu nunca quis reproduzir uma cena romântica com você.",
      "Eu nunca defendi um filme ruim como se fosse uma obra-prima.",
      "Eu nunca montei uma playlist para deixar o clima interessante.",
      "Eu nunca dancei na cozinha como se fosse um palco.",
      "Eu nunca cantei no seu ouvido só para ver sua reação.",
      "Eu nunca dediquei uma música e fiquei esperando você entender.",
      "Eu nunca quis aprender uma dança só para impressionar você.",
      "Eu nunca ensaiei uma frase provocante e ri na hora de falar.",
      "Eu nunca abracei seu travesseiro quando você levantou.",
      "Eu nunca tive uma ideia brilhante bem na hora de dormir.",
      "Eu nunca transformei uma mania sua em apelido carinhoso.",
      "Eu nunca falei dormindo e acordei querendo saber o assunto.",
      "Eu nunca fiz uma lista de aventuras que quero viver com você.",
      "Eu nunca quis largar a rotina por um projeto completamente novo.",
      "Eu nunca sonhei que nós dois tínhamos um talento impossível.",
      "Eu nunca conversei com uma planta esperando colaboração.",
      "Eu nunca desejei que um domingo a dois durasse uma semana.",
      "Eu nunca mandei uma mensagem provocante estando ao seu lado.",
      "Eu nunca programei um lembrete só para fazer você sorrir.",
      "Eu nunca desliguei minhas notificações para aproveitar nós dois.",
      "Eu nunca usei inteligência artificial para planejar uma surpresa.",
      "Eu nunca perdi para você num jogo e pedi revanche imediata.",
      "Eu nunca apostei uma massagem numa partida.",
      "Eu nunca inventei coragem para experimentar um esporte radical.",
      "Eu nunca fiz pose de atleta depois de subir uma escada.",
      "Eu nunca quis fazer uma trilha que terminasse numa cachoeira.",
      "Eu nunca tentei acompanhar seu treino só para me exibir.",
      "Eu nunca quis ir a uma festa com uma fantasia combinando com a sua.",
      "Eu nunca puxei você para dançar antes de tocar nossa música.",
      "Eu nunca transformei uma noite comum numa festa para dois.",
      "Eu nunca fiz um brinde ao nosso talento de causar juntos.",
      "Eu nunca fiquei até o fim da festa por causa de uma música.",
      "Eu nunca imaginei um nome extravagante para nosso futuro pet.",
      "Eu nunca perdi espaço no sofá para um animal minúsculo.",
      "Eu nunca falei com um cachorro usando voz de bebê.",
      "Eu nunca quis adotar um animal depois de ver uma foto.",
      "Eu nunca comprei um brinquedo para pet e me diverti mais que ele.",
      "Eu nunca desafiei você a me fazer rir sem encostar em mim.",
      "Eu nunca sustentei seu olhar só para aumentar a tensão.",
      "Eu nunca pedi um beijo como prêmio por uma vitória insignificante.",
      "Eu nunca inventei um código para dizer que quero carinho.",
      "Eu nunca fiz uma surpresa que exigia você fechar os olhos.",
      "Eu nunca cheguei bem perto só para falar uma bobagem.",
      "Eu nunca propus um encontro em que cada um escolhesse metade do plano.",
      "Eu nunca tentei fazer uma massagem e acabei provocando cócegas.",
      "Eu nunca tive vontade de repetir um encontro nosso nos mínimos detalhes.",
      "Eu nunca deixei você escolher meu próximo desafio só para testar sua ousadia.",
    ],
  },
  provavel: {
    fofo: [
      "Quem é mais provável de chorar no nosso casamento?",
      "Quem é mais provável de dizer eu te amo primeiro no dia?",
      "Quem é mais provável de planejar um encontro surpresa?",
      "Quem é mais provável de guardar cada presente?",
      "Quem é mais provável de sentir saudade primeiro?",
      "Quem é mais provável de escrever uma carta de amor?",
      "Quem é mais provável de querer um pet primeiro?",
      "Quem é mais provável de lembrar de todas as datas?",
      "Quem é mais provável de fazer café da manhã na cama?",
      "Quem é mais provável de pedir desculpa primeiro?",
      "Quem é mais provável de dormir abraçado(a) a noite toda?",
      "Quem é mais provável de chorar vendo filme romântico?",
      "Quem é mais provável de mandar bom dia primeiro?",
      "Quem é mais provável de cuidar do outro quando está doente?",
      "Quem é mais provável de dar o último pedaço da comida?",
      "Quem é mais provável de montar um álbum nosso?",
      "Quem é mais provável de fazer uma playlist pro outro?",
      "Quem é mais provável de pedir em casamento?",
      "Quem é mais provável de ficar bobo(a) olhando o outro dormir?",
      "Quem é mais provável de ligar só pra ouvir a voz?",
      "Quem é mais provável de acordar cedo para preparar um café da manhã a dois?",
      "Quem é mais provável de pedir mais cinco minutinhos de abraço?",
      "Quem é mais provável de deixar um bilhete fofo na mochila do outro?",
      "Quem é mais provável de mandar uma mensagem carinhosa no meio do dia?",
      "Quem é mais provável de inventar um apelido inspirado em comida?",
      "Quem é mais provável de transformar uma ida ao mercado em um encontro?",
      "Quem é mais provável de levar um casaco pensando no frio do outro?",
      "Quem é mais provável de fazer carinho até o outro dormir?",
      "Quem é mais provável de lembrar de beber água só depois de um lembrete?",
      "Quem é mais provável de guardar lembrancinhas dos passeios do casal?",
      "Quem é mais provável de preparar um jantar romântico com o que tiver na geladeira?",
      "Quem é mais provável de queimar a torrada enquanto canta na cozinha?",
      "Quem é mais provável de dividir o último pedacinho de chocolate?",
      "Quem é mais provável de inventar uma receita de sobremesa para o casal?",
      "Quem é mais provável de pedir pizza para comemorar uma pequena conquista?",
      "Quem é mais provável de escolher um restaurante só pela sobremesa?",
      "Quem é mais provável de fazer panquecas em formato de coração?",
      "Quem é mais provável de querer provar todos os sabores de sorvete?",
      "Quem é mais provável de montar um piquenique cheio de comidinhas favoritas?",
      "Quem é mais provável de decorar um bolo com as iniciais do casal?",
      "Quem é mais provável de planejar uma viagem inteira em uma noite?",
      "Quem é mais provável de levar metade do guarda-roupa para um fim de semana?",
      "Quem é mais provável de escolher uma pousada pelo café da manhã?",
      "Quem é mais provável de querer ver o nascer do sol na praia de mãos dadas?",
      "Quem é mais provável de fazer um álbum de cada viagem do casal?",
      "Quem é mais provável de sugerir uma viagem de trem só pela paisagem?",
      "Quem é mais provável de aprender frases em outro idioma para uma viagem?",
      "Quem é mais provável de comprar uma lembrancinha engraçada em cada destino?",
      "Quem é mais provável de sonhar com uma noite a dois sob a aurora boreal?",
      "Quem é mais provável de organizar uma viagem surpresa para um lugar tranquilo?",
      "Quem é mais provável de desenhar a planta da futura casa do casal?",
      "Quem é mais provável de querer uma varanda cheia de plantas?",
      "Quem é mais provável de escolher um sofá pensando nas sessões de abraço?",
      "Quem é mais provável de dar nomes aos eletrodomésticos da casa?",
      "Quem é mais provável de criar um cantinho de leitura para os dois?",
      "Quem é mais provável de montar os móveis sem olhar o manual?",
      "Quem é mais provável de querer luzinhas aconchegantes em todos os cômodos?",
      "Quem é mais provável de fazer uma planilha para realizar um sonho a dois?",
      "Quem é mais provável de imaginar como serão os domingos do casal no futuro?",
      "Quem é mais provável de criar uma tradição só dos dois para cada estação?",
      "Quem é mais provável de chorar numa cena fofa de animação?",
      "Quem é mais provável de dormir abraçado antes da metade do filme?",
      "Quem é mais provável de escolher uma comédia para animar um dia difícil?",
      "Quem é mais provável de decorar as falas do filme favorito do casal?",
      "Quem é mais provável de montar uma sessão de cinema com ingressos caseiros?",
      "Quem é mais provável de criar uma playlist para cada momento dos dois?",
      "Quem é mais provável de puxar uma dança lenta no meio da sala?",
      "Quem é mais provável de cantar errado com muita confiança?",
      "Quem é mais provável de aprender um instrumento para fazer uma serenata?",
      "Quem é mais provável de transformar a faxina em um show particular?",
      "Quem é mais provável de colocar vários alarmes e adiar todos?",
      "Quem é mais provável de organizar as roupas por cor?",
      "Quem é mais provável de conversar com as plantas enquanto rega?",
      "Quem é mais provável de rir antes de terminar de contar uma piada?",
      "Quem é mais provável de usar meias diferentes sem perceber?",
      "Quem é mais provável de criar figurinhas fofas com as fotos do casal?",
      "Quem é mais provável de programar um lembrete para a noite de jogos?",
      "Quem é mais provável de testar um aplicativo novo para organizar passeios?",
      "Quem é mais provável de tirar vinte fotos para registrar um abraço?",
      "Quem é mais provável de criar uma casa virtual para os dois em um jogo?",
      "Quem é mais provável de propor uma caminhada de mãos dadas depois do almoço?",
      "Quem é mais provável de transformar uma corrida em passeio para ver flores?",
      "Quem é mais provável de torcer com empolgação pelo outro numa competição?",
      "Quem é mais provável de sugerir uma aula de dança em dupla?",
      "Quem é mais provável de levar lanchinhos para uma trilha curta?",
      "Quem é mais provável de tentar uma pose de ioga e cair na risada?",
      "Quem é mais provável de querer aprender a andar de patins junto?",
      "Quem é mais provável de inventar uma comemoração fofa para cada gol?",
      "Quem é mais provável de topar acampar só para observar as estrelas a dois?",
      "Quem é mais provável de levar uma pipa para um encontro no parque?",
      "Quem é mais provável de fazer uma contagem regressiva para o aniversário do outro?",
      "Quem é mais provável de caprichar mais no embrulho do que no presente?",
      "Quem é mais provável de sugerir fantasias combinando para uma festa?",
      "Quem é mais provável de decorar a casa para uma comemoração dos dois?",
      "Quem é mais provável de organizar uma festa junina a dois na sala?",
      "Quem é mais provável de planejar uma festa de aniversário para o bichinho?",
      "Quem é mais provável de parar um passeio para admirar um cachorro fofo?",
      "Quem é mais provável de escolher um nome de comida para um animal de estimação?",
      "Quem é mais provável de construir um castelo de caixas para um gato?",
      "Quem é mais provável de tirar uma foto do casal combinando com o bichinho?",
      "Quem é mais provável de escrever uma lista de cem aventuras para viver a dois?",
      "Quem é mais provável de fazer uma cápsula do tempo com recordações do casal?",
      "Quem é mais provável de imaginar os dois velhinhos tomando café na varanda?",
      "Quem é mais provável de escrever um poema inspirado no sorriso do outro?",
      "Quem é mais provável de pintar um quadro para decorar o cantinho dos dois?",
      "Quem é mais provável de aprender crochê para fazer um presente quentinho?",
      "Quem é mais provável de sonhar em abrir uma cafeteria com o outro?",
      "Quem é mais provável de criar um livro ilustrado com aventuras do casal?",
      "Quem é mais provável de propor um dia sem telas para curtir a companhia do outro?",
      "Quem é mais provável de inventar uma constelação com o nome do casal?",
    ],
    engracado: [
      "Quem é mais provável de se perder num shopping?",
      "Quem é mais provável de queimar a comida?",
      "Quem é mais provável de rir num momento sério?",
      "Quem é mais provável de esquecer onde deixou o celular estando com ele na mão?",
      "Quem é mais provável de dormir no cinema?",
      "Quem é mais provável de ficar emburrado(a) com fome?",
      "Quem é mais provável de cair da cadeira?",
      "Quem é mais provável de demorar mais pra se arrumar?",
      "Quem é mais provável de falar dormindo?",
      "Quem é mais provável de virar meme?",
      "Quem é mais provável de comer o lanche do outro?",
      "Quem é mais provável de fazer drama por um machucadinho?",
      "Quem é mais provável de ganhar uma discussão?",
      "Quem é mais provável de ter medo de barata?",
      "Quem é mais provável de roubar a coberta?",
      "Quem é mais provável de cantar errado a música inteira?",
      "Quem é mais provável de desistir de um exercício no meio?",
      "Quem é mais provável de comprar algo inútil?",
      "Quem é mais provável de chegar atrasado(a)?",
      "Quem é mais provável de sobreviver a um apocalipse zumbi?",
      "Quem é mais provável de colocar cinco alarmes e ignorar todos?",
      "Quem é mais provável de sair com a camiseta do avesso?",
      "Quem é mais provável de sair usando um chinelo de cada cor?",
      "Quem é mais provável de procurar os óculos que estão na própria cabeça?",
      "Quem é mais provável de empurrar uma porta escrita puxe?",
      "Quem é mais provável de pedir desculpa depois de esbarrar num manequim?",
      "Quem é mais provável de rir da própria piada antes de terminar?",
      "Quem é mais provável de tropeçar no chão completamente liso?",
      "Quem é mais provável de ter a barriga roncando durante um silêncio?",
      "Quem é mais provável de roncar antes da abertura do filme acabar?",
      "Quem é mais provável de queimar pipoca e culpar o micro-ondas?",
      "Quem é mais provável de colocar sal no café sem perceber?",
      "Quem é mais provável de comer brigadeiro escondido com uma concha?",
      "Quem é mais provável de pedir delivery enquanto a comida está no forno?",
      "Quem é mais provável de derrubar molho na roupa logo na primeira garfada?",
      "Quem é mais provável de deixar só um biscoito no pacote para não jogar fora?",
      "Quem é mais provável de sujar seis panelas para fazer uma receita simples?",
      "Quem é mais provável de exagerar no alho e perfumar a casa inteira?",
      "Quem é mais provável de soprar o sorvete por puro reflexo?",
      "Quem é mais provável de servir miojo como se fosse um prato de restaurante?",
      "Quem é mais provável de levar uma mala enorme para passar uma noite fora?",
      "Quem é mais provável de chegar ao aeroporto um dia antes da viagem?",
      "Quem é mais provável de tentar abrir o quarto errado no hotel?",
      "Quem é mais provável de dormir no passeio que insistiu em fazer?",
      "Quem é mais provável de tirar cem fotos e aparecer de olhos fechados em todas?",
      "Quem é mais provável de seguir o mapa e acabar num estacionamento?",
      "Quem é mais provável de gastar mais com lembrancinhas do que com comida?",
      "Quem é mais provável de passar protetor e ficar com uma marca de mão?",
      "Quem é mais provável de trazer metade da areia da praia dentro da mala?",
      "Quem é mais provável de montar a barraca e descobrir que ficou sem porta?",
      "Quem é mais provável de transformar uma cadeira num armário de roupas usadas?",
      "Quem é mais provável de pedir desculpa para uma planta que esqueceu de regar?",
      "Quem é mais provável de lavar uma meia vermelha com todas as roupas brancas?",
      "Quem é mais provável de guardar uma caixa vazia porque ela é bonita?",
      "Quem é mais provável de usar a vassoura como microfone durante a faxina?",
      "Quem é mais provável de negociar verbalmente com uma aranha no banheiro?",
      "Quem é mais provável de guardar o controle remoto no congelador?",
      "Quem é mais provável de começar uma reforma por causa de um vídeo de 30 segundos?",
      "Quem é mais provável de esconder a bagunça no forno antes de receber visitas?",
      "Quem é mais provável de atender à campainha com espuma de shampoo na cabeça?",
      "Quem é mais provável de chorar num desenho sobre uma torradeira?",
      "Quem é mais provável de torcer pelo vilão porque ele tem um plano organizado?",
      "Quem é mais provável de adivinhar o final do filme e errar com muita confiança?",
      "Quem é mais provável de pausar a série para explicar uma teoria absurda?",
      "Quem é mais provável de cantar a letra errada com total convicção?",
      "Quem é mais provável de escolher no karaokê uma música que não consegue cantar?",
      "Quem é mais provável de ensaiar uma coreografia e esquecer tudo na hora?",
      "Quem é mais provável de criar uma playlist dramática para lavar a louça?",
      "Quem é mais provável de inventar uma trilha sonora para as tarefas do casal?",
      "Quem é mais provável de ouvir a mesma música até decorar até a respiração?",
      "Quem é mais provável de gravar um áudio inteiro com o microfone bloqueado?",
      "Quem é mais provável de entrar numa chamada séria com filtro de batata?",
      "Quem é mais provável de esquecer a senha que acabou de criar?",
      "Quem é mais provável de agradecer ao atendimento automático?",
      "Quem é mais provável de pedir ajuda à IA para escolher o jantar?",
      "Quem é mais provável de abrir tantas abas que o computador pede socorro?",
      "Quem é mais provável de derrubar o próprio celular no rosto deitado?",
      "Quem é mais provável de atualizar o computador bem na hora de usar?",
      "Quem é mais provável de dar nome e sobrenome ao aspirador robô?",
      "Quem é mais provável de ver um tutorial e achar que já pode dar um curso?",
      "Quem é mais provável de ir à academia e cansar procurando um ângulo para a foto?",
      "Quem é mais provável de fazer gol contra e comemorar por reflexo?",
      "Quem é mais provável de cair na ioga tentando parecer uma pessoa zen?",
      "Quem é mais provável de contar a corrida atrás do ônibus como treino?",
      "Quem é mais provável de inventar uma regra para não perder no jogo?",
      "Quem é mais provável de andar pela sala para completar a meta de passos?",
      "Quem é mais provável de comemorar a vitória antes da hora e perder?",
      "Quem é mais provável de fazer alongamento para alcançar a pipoca no sofá?",
      "Quem é mais provável de descer da bicicleta para fazer uma curva fácil?",
      "Quem é mais provável de abandonar a corrida ao sentir cheiro de padaria?",
      "Quem é mais provável de começar os parabéns no tom mais impossível?",
      "Quem é mais provável de exagerar na decoração e bloquear a porta com balões?",
      "Quem é mais provável de comer um doce que fazia parte da decoração?",
      "Quem é mais provável de dormir sentado no meio de uma festa barulhenta?",
      "Quem é mais provável de aparecer fantasiado numa festa que não era à fantasia?",
      "Quem é mais provável de dançar como se estivesse desviando de abelhas?",
      "Quem é mais provável de gritar mais alto que o barulho do balão estourando?",
      "Quem é mais provável de sair da quermesse carregando três pratos e um prêmio?",
      "Quem é mais provável de criar uma voz diferente para cada animal de casa?",
      "Quem é mais provável de organizar um aniversário com convites para o cachorro?",
      "Quem é mais provável de pedir licença ao gato para sentar no próprio sofá?",
      "Quem é mais provável de perder uma discussão para um papagaio?",
      "Quem é mais provável de tentar treinar o cachorro e acabar obedecendo a ele?",
      "Quem é mais provável de mudar de caminho para não pisar numa fila de formigas?",
      "Quem é mais provável de sonhar que venceu um monstro usando um boleto?",
      "Quem é mais provável de planejar uma casa com escorregador no lugar da escada?",
      "Quem é mais provável de planejar a aposentadoria antes de organizar a semana?",
      "Quem é mais provável de sonhar em abrir uma padaria sem saber fazer pão?",
      "Quem é mais provável de comprar pijamas combinando para o casal e o cachorro?",
      "Quem é mais provável de ensaiar um discurso para um prêmio que nem existe?",
    ],
    safado: SAFADO_PROVAVEL,
    apimentado: [
      "Quem é mais provável de roubar um beijo do nada?",
      "Quem é mais provável de provocar o outro de propósito?",
      "Quem é mais provável de mandar uma mensagem ousada?",
      "Quem é mais provável de não resistir a um olhar?",
      "Quem é mais provável de puxar o outro pra dançar colado?",
      "Quem é mais provável de ficar vermelho(a) primeiro?",
      "Quem é mais provável de pedir mais um beijo?",
      "Quem é mais provável de sussurrar algo no ouvido?",
      "Quem é mais provável de ficar sem graça com um elogio?",
      "Quem é mais provável de planejar um encontro romântico à luz de velas?",
      "Quem é mais provável de dar um abraço por trás?",
      "Quem é mais provável de perder a concentração olhando o outro?",
      "Quem é mais provável de fazer uma declaração ousada?",
      "Quem é mais provável de não querer soltar no abraço?",
      "Quem é mais provável de beijar no meio de uma briga boba?",
      "Quem é mais provável de pedir carinho primeiro?",
      "Quem é mais provável de morder o lábio sem perceber?",
      "Quem é mais provável de ganhar no jogo da sedução?",
      "Quem é mais provável de roubar o cobertor e oferecer um abraço como compensação?",
      "Quem é mais provável de apertar a soneca só para ficar agarradinho?",
      "Quem é mais provável de transformar o café na cama numa provocação?",
      "Quem é mais provável de interromper a louça com um abraço demorado?",
      "Quem é mais provável de usar a roupa do outro para desfilar pela casa?",
      "Quem é mais provável de desafiar o outro a não sorrir durante um beijo?",
      "Quem é mais provável de tomar a iniciativa numa noite especial?",
      "Quem é mais provável de deixar um bilhete atrevido no travesseiro?",
      "Quem é mais provável de trocar a série por uma sessão de carinhos?",
      "Quem é mais provável de fazer charme para escapar de uma tarefa?",
      "Quem é mais provável de comer a sobremesa antes do jantar?",
      "Quem é mais provável de inventar uma receita ousada e exigir nota dez?",
      "Quem é mais provável de pedir comida apimentada e se arrepender na primeira garfada?",
      "Quem é mais provável de roubar a última batata do prato do outro?",
      "Quem é mais provável de cozinhar com uma trilha sonora sedutora?",
      "Quem é mais provável de organizar uma degustação de olhos vendados?",
      "Quem é mais provável de transformar a farinha numa guerra na cozinha?",
      "Quem é mais provável de acordar de madrugada para fazer brigadeiro?",
      "Quem é mais provável de defender abacaxi na pizza com um discurso apaixonado?",
      "Quem é mais provável de ganhar uma competição de comer tacos?",
      "Quem é mais provável de comprar passagens por impulso?",
      "Quem é mais provável de escolher a hospedagem só pela banheira?",
      "Quem é mais provável de quase perder o voo comprando lanches?",
      "Quem é mais provável de convencer o outro a acampar sem sinal de internet?",
      "Quem é mais provável de encarar uma cachoeira gelada sem reclamar?",
      "Quem é mais provável de planejar um passeio sob as estrelas?",
      "Quem é mais provável de levar uma mala enorme para um fim de semana?",
      "Quem é mais provável de fazer o casal se perder mesmo usando o mapa?",
      "Quem é mais provável de propor uma viagem sem destino definido?",
      "Quem é mais provável de beijar o outro no topo de uma montanha?",
      "Quem é mais provável de planejar uma casa com janelas gigantes?",
      "Quem é mais provável de insistir em colocar uma rede na sala?",
      "Quem é mais provável de adotar uma planta e tratar como filha?",
      "Quem é mais provável de montar um móvel sem ler o manual?",
      "Quem é mais provável de mudar a decoração de madrugada?",
      "Quem é mais provável de ocupar o armário inteiro e ainda pedir espaço?",
      "Quem é mais provável de transformar a faxina num show particular?",
      "Quem é mais provável de propor um mês sem compras por impulso?",
      "Quem é mais provável de criar um cantinho para encontros dentro de casa?",
      "Quem é mais provável de sonhar em morar numa casinha na praia?",
      "Quem é mais provável de chorar num filme e culpar a alergia?",
      "Quem é mais provável de escolher terror só para pedir um abraço apertado?",
      "Quem é mais provável de imitar um vilão durante o jantar?",
      "Quem é mais provável de decorar todas as falas da comédia favorita?",
      "Quem é mais provável de cantar uma música sedutora completamente desafinado?",
      "Quem é mais provável de fazer uma playlist para esquentar o clima dos dois?",
      "Quem é mais provável de puxar uma dança coladinha no meio da sala?",
      "Quem é mais provável de disputar o microfone no karaokê?",
      "Quem é mais provável de comprar ingressos para um show sem pensar duas vezes?",
      "Quem é mais provável de transformar o banho num concerto?",
      "Quem é mais provável de dormir bem no final do filme?",
      "Quem é mais provável de falar dormindo e revelar um sonho absurdo?",
      "Quem é mais provável de organizar as meias por cor?",
      "Quem é mais provável de acumular canecas na cabeceira?",
      "Quem é mais provável de usar dez alarmes e não levantar com nenhum?",
      "Quem é mais provável de inventar um apelido ousado que só os dois entendem?",
      "Quem é mais provável de provocar o outro só com um olhar?",
      "Quem é mais provável de mandar uma mensagem atrevida na hora do almoço?",
      "Quem é mais provável de prolongar a despedida pedindo mais um beijo?",
      "Quem é mais provável de propor um desafio de massagem?",
      "Quem é mais provável de largar tudo para abrir um negócio?",
      "Quem é mais provável de querer um ano sabático viajando de motorhome?",
      "Quem é mais provável de escrever um livro sobre as aventuras do casal?",
      "Quem é mais provável de planejar a aposentadoria antes dos trinta?",
      "Quem é mais provável de aprender um idioma para preparar uma viagem surpresa?",
      "Quem é mais provável de querer casar com os pés na areia?",
      "Quem é mais provável de sugerir tatuagens combinando?",
      "Quem é mais provável de montar uma lista de desejos ousados para o ano?",
      "Quem é mais provável de transformar um hobby em profissão?",
      "Quem é mais provável de guardar dinheiro para realizar um sonho do outro?",
      "Quem é mais provável de conversar com o robô aspirador?",
      "Quem é mais provável de automatizar as luzes para criar um clima romântico?",
      "Quem é mais provável de esquecer a senha que acabou de criar?",
      "Quem é mais provável de ganhar no videogame e cobrar um beijo como prêmio?",
      "Quem é mais provável de usar um filtro absurdo numa foto romântica?",
      "Quem é mais provável de passar horas escolhendo o papel de parede do computador?",
      "Quem é mais provável de comprar um aparelho só porque achou bonito?",
      "Quem é mais provável de criar uma figurinha com a cara de sono do outro?",
      "Quem é mais provável de fazer uma planilha para planejar encontros?",
      "Quem é mais provável de ficar um dia offline para curtir a companhia do outro?",
      "Quem é mais provável de propor uma corrida valendo massagem?",
      "Quem é mais provável de topar um esporte radical sem piscar?",
      "Quem é mais provável de competir até na hora do alongamento?",
      "Quem é mais provável de comemorar um gol com uma dança provocante?",
      "Quem é mais provável de chegar à festa e puxar o outro para a pista?",
      "Quem é mais provável de inventar uma festa temática só para os dois?",
      "Quem é mais provável de sair da festa cedo para prolongar a noite em casa?",
      "Quem é mais provável de querer adotar um cachorro enorme morando num apê?",
      "Quem é mais provável de deixar o pet ocupar seu lado da cama?",
      "Quem é mais provável de fazer voz de bebê para conversar com um gato?",
    ],
  },
};
