// Nível "Safado" — quente e provocante, só sobre os dois, sem nada gráfico.
export const SAFADO_NUNCA = [
  "Eu nunca fiquei com vontade de te tirar a roupa só com o olhar",
  "Eu nunca imaginei a gente se pegando num lugar público",
  "Eu nunca pensei em você de um jeito bem safado no meio do dia",
  "Eu nunca quis te beijar no pescoço até você arrepiar",
  "Eu nunca fiquei com tesão só lendo uma mensagem sua",
  "Eu nunca imaginei você usando só uma camiseta minha",
  "Eu nunca pensei em te acordar com beijos bem safados",
  "Eu nunca quis te prensar na parede pra te beijar",
  "Eu nunca tive um sonho quente com você",
  "Eu nunca fiquei imaginando o que faria com você numa banheira",
  "Eu nunca quis morder sua boca de propósito",
  "Eu nunca imaginei a gente trancado num quarto de hotel o fim de semana todo",
  "Eu nunca pensei numa lingerie/cueca que queria te ver usando",
  "Eu nunca fiquei louco(a) pra sussurrar uma safadeza no seu ouvido",
  "Eu nunca quis te provocar por baixo da mesa",
  "Eu nunca imaginei um banho a dois com você",
  "Eu nunca pensei em te vendar e te deixar adivinhando",
  "Eu nunca senti vontade de te agarrar assim que te vi",
  "Eu nunca fiquei olhando seu corpo quando você não tava percebendo",
  "Eu nunca quis fazer uma massagem em você que terminasse em outra coisa",
  "Eu nunca imaginei a gente se pegando no carro",
  "Eu nunca pensei em mandar uma foto bem provocante pra você",
  "Eu nunca quis tirar sua roupa bem devagar",
  "Eu nunca tive uma fantasia com você que nunca contei",
  "Eu nunca fiquei com vontade de te morder inteiro(a)",
  "Eu nunca imaginei a gente numa noite inteira sem dormir, e não era conversando",
  "Eu nunca pensei em te deixar marcas de beijo",
  "Eu nunca quis te dominar um pouquinho",
  "Eu nunca quis ser dominado(a) por você",
  "Eu nunca fiquei excitado(a) só de lembrar do seu cheiro",
  "Eu nunca pensei num lugar ousado onde queria te beijar",
  "Eu nunca imaginei a gente dançando colado até perder o controle",
  "Eu nunca quis te ouvir gemendo meu nome",
  "Eu nunca pensei em brincar com gelo em você",
  "Eu nunca quis passar chocolate em você só pra tirar com a boca",
];
export const SAFADO_PROVAVEL = [
  "Quem é mais provável de começar a provocação primeiro?",
  "Quem é mais provável de mandar uma mensagem safada do nada?",
  "Quem é mais provável de tirar a roupa do outro primeiro?",
  "Quem é mais provável de propor uma pegação em lugar proibido?",
  "Quem é mais provável de ficar com tesão primeiro?",
  "Quem é mais provável de pedir pra repetir a noite?",
  "Quem é mais provável de comprar uma lingerie/cueca pra provocar?",
  "Quem é mais provável de sussurrar uma safadeza em público?",
  "Quem é mais provável de deixar marca de chupão?",
  "Quem é mais provável de puxar o outro pro banho?",
  "Quem é mais provável de ter a fantasia mais ousada?",
  "Quem é mais provável de não aguentar esperar chegar em casa?",
  "Quem é mais provável de provocar por baixo da mesa?",
  "Quem é mais provável de mandar a foto mais ousada?",
  "Quem é mais provável de vendar o outro?",
  "Quem é mais provável de ser mais barulhento(a)?",
  "Quem é mais provável de morder durante o beijo?",
  "Quem é mais provável de acordar o outro com segundas intenções?",
  "Quem é mais provável de comandar a noite?",
  "Quem é mais provável de pedir massagem querendo outra coisa?",
  "Quem é mais provável de se pegar no carro?",
  "Quem é mais provável de rasgar a roupa na pressa?",
  "Quem é mais provável de ficar vermelho(a) com uma safadeza?",
  "Quem é mais provável de sugerir algo novo na cama?",
  "Quem é mais provável de ficar pelado(a) primeiro?",
  "Quem é mais provável de provocar sabendo que não dá pra fazer nada?",
  "Quem é mais provável de esquecer a vergonha de vez?",
  "Quem é mais provável de pedir \"de novo\"?",
  "Quem é mais provável de fazer um strip-tease?",
  "Quem é mais provável de ligar só pra falar safadeza?",
];
