export type Theme = { name: string; items: string[] };

export const THEMES: Theme[] = [
  { name: "Comidas", items: ["Pizza","Hambúrguer","Sushi","Lasanha","Pudim","Coxinha"] },
  { name: "Países", items: ["Brasil","Japão","Itália","França","Egito","Canadá"] },
  { name: "Animais", items: ["Leão","Golfinho","Elefante","Pinguim","Cachorro","Girafa"] },
  { name: "Cidades", items: ["Paris","Tóquio","Nova York","Rio de Janeiro","Londres","Dubai"] },
  { name: "Esportes", items: ["Futebol","Basquete","Tênis","Vôlei","Boxe","Natação"] },
  { name: "Tecnologia", items: ["Celular","Notebook","Videogame","Drone","Robô","Smartwatch"] },
  { name: "Casa", items: ["Sofá","Geladeira","Cama","Chuveiro","Televisão","Micro-ondas"] },
  { name: "Viagem", items: ["Avião","Hotel","Passaporte","Mala","Aeroporto","Mapa"] },
  { name: "Natureza", items: ["Montanha","Cachoeira","Floresta","Vulcão","Deserto","Rio"] },
  { name: "Música", items: ["Violão","Piano","Bateria","Microfone","Show","Cantor"] },
  { name: "Moda", items: ["Vestido","Tênis","Jaqueta","Bolsa","Boné","Óculos"] },
  { name: "Festas", items: ["Aniversário","Casamento","Carnaval","Réveillon","Balada","Formatura"] },
  { name: "Doces", items: ["Chocolate","Sorvete","Brigadeiro","Bolo","Donut","Picolé"] },
];

export const CLUES: Record<string, string[]> = {
  Pizza:["costuma ser dividida em fatias","o queijo derretido chama atenção","pode ter borda fina ou recheada"],
  Hambúrguer:["normalmente é montado em camadas","o pão fica por fora do recheio","pode receber vários complementos"],
  Sushi:["costuma ser servido em pedaços pequenos","é muito associado à culinária japonesa","pode levar arroz e ingredientes crus"],
  Lasanha:["é montada em várias camadas","o molho aparece entre as camadas","geralmente é servida em porções"],
  Pudim:["tem textura macia e cremosa","costuma ter uma calda por cima","normalmente é desenformado"],
  Coxinha:["tem formato parecido com uma gota","o recheio tradicional é frango","é muito comum em festas brasileiras"],
  Brasil:["é o maior país da América do Sul","o português é a língua oficial","a bandeira tem verde, amarelo, azul e branco"],
  Japão:["é formado por várias ilhas","mistura tecnologia e tradições antigas","a flor de cerejeira é um símbolo conhecido"],
  Itália:["Roma é a capital","é muito associada a massas e pizzas","tem formato parecido com uma bota no mapa"],
  França:["Paris é a capital","a Torre Eiffel é um símbolo famoso","é muito associada à gastronomia e à moda"],
  Egito:["o rio Nilo atravessa o país","as pirâmides são um símbolo conhecido","fica no nordeste da África"],
  Canadá:["a folha de bordo aparece na bandeira","é conhecido por seus invernos rigorosos","fica na América do Norte"],
  Leão:["o macho pode ter uma grande juba","é um predador de grande porte","vive em grupos"],
  Golfinho:["vive na água e precisa subir para respirar","costuma viver em grupos","é conhecido pela inteligência"],
  Elefante:["usa a tromba para pegar coisas","tem enormes orelhas","é um dos maiores animais terrestres"],
  Pinguim:["não consegue voar","usa as asas para nadar","é associado a regiões frias"],
  Cachorro:["tem olfato muito desenvolvido","é um dos animais domésticos mais comuns","existem muitas raças"],
  Girafa:["tem o pescoço extremamente comprido","usa a língua para alcançar folhas","é um animal muito alto"],
  Paris:["a Torre Eiffel é um cartão-postal","fica às margens do rio Sena","é muito ligada à arte e à moda"],
  Tóquio:["é a capital do Japão","tem uma enorme rede ferroviária","mistura bairros modernos e tradicionais"],
  "Nova York":["Manhattan é uma área muito conhecida","tem muitos arranha-céus","a Estátua da Liberdade fica na cidade"],
  "Rio de Janeiro":["o Cristo Redentor é um cartão-postal","tem praias muito conhecidas","o Pão de Açúcar fica na cidade"],
  Londres:["o Big Ben é um símbolo","os ônibus vermelhos são famosos","é a capital do Reino Unido"],
  Dubai:["é conhecida por construções muito altas","fica nos Emirados Árabes Unidos","é associada a luxo e arquitetura moderna"],
  Futebol:["dois times tentam marcar gols","é jogado com uma bola","tem onze jogadores de cada lado em campo"],
  Basquete:["envolve arremessos em uma cesta","é jogado em uma quadra","a bola é conduzida com as mãos"],
  Tênis:["é jogado com raquete","uma rede divide os lados","pode ser disputado individualmente ou em duplas"],
  Vôlei:["uma rede divide a quadra","a bola não pode tocar o chão do próprio lado","as equipes fazem rodízio"],
  Boxe:["os competidores usam luvas","é uma modalidade de combate","os golpes são feitos principalmente com as mãos"],
  Natação:["é praticada dentro da água","há diferentes estilos","pode ser disputada em piscinas"],
  Celular:["é portátil","possui aplicativos","é usado para comunicação"],
  Notebook:["é um computador portátil","tem tela e teclado juntos","pode ser levado para vários lugares"],
  Videogame:["é usado para jogar","pode ter controle","existem muitos gêneros diferentes"],
  Drone:["pode voar sem piloto dentro","é controlado remotamente","pode carregar uma câmera"],
  Robô:["é uma máquina programada","pode executar tarefas","pode ter sensores"],
  Smartwatch:["é usado no pulso","tem funções digitais","pode mostrar notificações"],
  Sofá:["é um móvel para sentar","costuma ficar na sala","pode acomodar várias pessoas"],
  Geladeira:["mantém alimentos refrigerados","fica ligada na tomada","tem portas e prateleiras"],
  Cama:["é usada para dormir","fica normalmente no quarto","pode ter colchão e travesseiro"],
  Chuveiro:["é usado durante o banho","fica em uma área molhada","libera água de cima"],
  Televisão:["tem uma tela","pode transmitir programas","é comum em salas"],
  "Micro-ondas":["aquece alimentos rapidamente","tem uma porta","possui um painel de controle"],
  Avião:["viaja pelo ar","tem asas","decola e pousa em aeroportos"],
  Hotel:["recebe viajantes","oferece quartos","pode ter recepção"],
  Passaporte:["é um documento","é usado em viagens internacionais","tem páginas para registros"],
  Mala:["serve para transportar roupas","tem alça","é comum em aeroportos"],
  Aeroporto:["recebe aviões","tem áreas de embarque","pode ter esteiras de bagagem"],
  Mapa:["ajuda na localização","pode mostrar estradas","representa lugares"],
  Montanha:["é uma grande elevação natural","pode ter neve no topo","é comum em paisagens"],
  Cachoeira:["tem água caindo de uma altura","pode ficar em uma área de mata","atrai visitantes"],
  Floresta:["tem muitas árvores","abriga diversos animais","pode ocupar uma área enorme"],
  Vulcão:["pode liberar lava","é uma formação geológica","pode ter uma cratera"],
  Deserto:["recebe pouca chuva","pode ter grandes áreas de areia","tem clima muito seco"],
  Rio:["é um curso natural de água","pode atravessar cidades","desemboca em outro corpo d'água"],
  Violão:["tem cordas","pode ser tocado com palheta","é muito usado em rodas de música"],
  Piano:["tem teclas","é um instrumento grande","pode aparecer em concertos"],
  Bateria:["é formada por peças de percussão","pode ser tocada com baquetas","marca o ritmo de músicas"],
  Microfone:["capta a voz","é usado em apresentações","pode ser conectado a caixas de som"],
  Show:["é uma apresentação para público","pode ter música","acontece em um palco"],
  Cantor:["usa a voz para se apresentar","pode trabalhar com uma banda","faz apresentações para público"],
  Vestido:["é uma peça de roupa","pode ter vários estilos","é usado em diferentes ocasiões"],
  Tênis:["é um tipo de calçado","é usado no dia a dia","pode ter sola de borracha"],
  Jaqueta:["é usada na parte de cima do corpo","pode proteger do frio","tem vários modelos"],
  Bolsa:["serve para carregar objetos","pode ser usada no ombro","tem muitos tamanhos"],
  Boné:["é usado na cabeça","tem uma aba","pode ter estampas"],
  Óculos:["fica diante dos olhos","pode corrigir a visão","também pode ser usado como acessório"],
  Aniversário:["acontece todos os anos","costuma ter comemoração","pode ter bolo"],
  Casamento:["é uma celebração","pode reunir familiares","costuma ter cerimônia"],
  Carnaval:["tem música e fantasias","é famoso pelos desfiles","atrai grandes multidões"],
  Réveillon:["marca a chegada de um novo ano","é comemorado à noite","pode ter fogos"],
  Balada:["costuma acontecer à noite","tem música","é ligada à dança"],
  Formatura:["marca o fim de uma etapa","pode ter cerimônia","reúne estudantes e familiares"],
  Chocolate:["é feito a partir de cacau","pode ser ao leite ou amargo","é uma sobremesa popular"],
  Sorvete:["é gelado","pode ter vários sabores","é servido em bolas ou porções"],
  Brigadeiro:["é um doce brasileiro","leva chocolate","costuma ser enrolado em pequenas porções"],
  Bolo:["é assado","pode ter cobertura","é comum em festas"],
  Donut:["tem formato circular","pode ter cobertura","tem um furo no centro"],
  Picolé:["é congelado","tem um palito","pode ter vários sabores"],
};

