import { useMemo, useState } from "react";
import { Backpack, Campfire, Car, Check, Compass, Flame, Lock, RotateCcw, Shield, Sparkles, TentTree, TreePine, WandSparkles } from "lucide-react";
import { useGameChannel, type Me } from "./useGameChannel";

type Ready = { gu: boolean; li: boolean };

function Gate({ peerOnline, ready, me, onReady, started, onStart, title, subtitle, children }: {
  peerOnline: boolean; ready: Ready; me: Me; onReady: () => void; started: boolean; onStart: () => void;
  title: string; subtitle: string; children: React.ReactNode;
}) {
  if (!peerOnline) return <div className="h-full min-h-[420px] flex items-center justify-center p-6 text-center"><div className="max-w-sm rounded-3xl border border-white/10 bg-white/[0.04] p-7"><Lock className="mx-auto mb-4 text-amber-300" size={30}/><h3 className="font-black text-lg">Aguardando o outro jogador</h3><p className="mt-2 text-sm text-white/50">Os dois precisam estar dentro deste jogo para continuar.</p></div></div>;
  if (!started) return <div className="h-full overflow-y-auto p-4"><div className="mx-auto max-w-xl pb-8"><div className="rounded-3xl border border-white/10 bg-gradient-to-br from-white/[0.08] to-white/[0.02] p-6"><div className="flex items-center gap-3"><Sparkles className="text-fuchsia-300" size={22}/><div><h2 className="text-xl font-black">{title}</h2><p className="text-xs text-white/50">{subtitle}</p></div></div><div className="mt-6 grid grid-cols-2 gap-3">{(["gu","li"] as Me[]).map(p=><div key={p} className="rounded-2xl border border-white/10 bg-black/20 p-4"><p className="text-xs uppercase tracking-widest text-white/40">{p==="gu"?"BB Gu":"BB Li"}</p><p className={"mt-2 text-sm font-bold "+(ready[p]?"text-emerald-300":"text-white/60")}>{ready[p]?"Pronto":"Ainda não"}</p></div>)}</div><button onClick={onReady} disabled={ready[me]} className="mt-5 w-full rounded-2xl bg-gradient-to-r from-fuchsia-500 to-indigo-600 py-3 font-black disabled:opacity-50">{ready[me]?"Você está pronto":"Estou pronto"}</button><button onClick={onStart} disabled={!ready.gu||!ready.li} className="mt-2 w-full rounded-2xl bg-white/10 py-3 text-sm font-bold disabled:opacity-30">{ready.gu&&ready.li?"Começar partida":"Os dois precisam estar prontos"}</button></div></div></div>;
  return <div className="h-full overflow-y-auto">{children}</div>;
}

/* MALA TETRIS */
type Shape = {x:number;y:number};
type BagItem = {id:string;name:string;icon:string;shape:Shape[];owner:Me;placed:boolean;points:number};
const BAG_ITEMS:BagItem[]=[
{id:"shirt",name:"2 blusas",icon:"BL",shape:[{x:0,y:0},{x:1,y:0}],owner:"gu",placed:false,points:2},
{id:"shoe",name:"Tênis",icon:"TN",shape:[{x:0,y:0},{x:0,y:1},{x:0,y:2}],owner:"gu",placed:false,points:3},
{id:"camera",name:"Câmera",icon:"CM",shape:[{x:0,y:0},{x:1,y:0},{x:0,y:1},{x:1,y:1}],owner:"gu",placed:false,points:4},
{id:"dryer",name:"Secador",icon:"SC",shape:[{x:0,y:0},{x:1,y:0},{x:2,y:0}],owner:"li",placed:false,points:3},
{id:"coat",name:"Casaco",icon:"CA",shape:[{x:0,y:0},{x:0,y:1},{x:1,y:1},{x:2,y:1}],owner:"li",placed:false,points:4},
{id:"gift",name:"Presente",icon:"PR",shape:[{x:0,y:0},{x:1,y:0},{x:1,y:1}],owner:"li",placed:false,points:3},
];
const BAG_EVENTS=["Vai chover no destino.","A temperatura caiu 10 graus.","Vocês decidiram levar mais uma lembrança."];
type BagState={phase:"lobby"|"playing"|"done";ready:Ready;grid:(string|null)[];items:BagItem[];turn:Me;turnCount:number;eventIndex:number;message:string};
const bagInitial:BagState={phase:"lobby",ready:{gu:false,li:false},grid:Array(48).fill(null),items:BAG_ITEMS,turn:"gu",turnCount:0,eventIndex:0,message:"Escolham um item e encaixem na mala."};

export function MalaTetris({me}:{me:Me}){
 const {state,setState,peerOnline}=useGameChannel<BagState>("mala-tetris",me,bagInitial);
 const [selected,setSelected]=useState<string|null>(null); const [rotation,setRotation]=useState(0);
 const ready=()=>setState(s=>({...s,ready:{...s.ready,[me]:true}}));
 const start=()=>{if(peerOnline&&state.ready.gu&&state.ready.li)setState({...state,phase:"playing",message:"BB Gu começa. Cada jogador coloca seus próprios itens."});};
 const shape=(src:Shape[])=>{let s=src.map(p=>({...p}));for(let i=0;i<rotation;i++)s=s.map(p=>({x:-p.y,y:p.x}));const mx=Math.min(...s.map(p=>p.x)),my=Math.min(...s.map(p=>p.y));return s.map(p=>({x:p.x-mx,y:p.y-my}));};
 const place=(index:number)=>{if(state.phase!=="playing"||state.turn!==me||!selected)return;const item=state.items.find(i=>i.id===selected);if(!item||item.placed)return;const sh=shape(item.shape),row=Math.floor(index/8),col=index%8;if(!sh.every(p=>{const r=row+p.y,c=col+p.x;return r>=0&&r<6&&c>=0&&c<8&&!state.grid[r*8+c]}))return;const grid=[...state.grid];sh.forEach(p=>{grid[(row+p.y)*8+col+p.x]=item.id});const items=state.items.map(i=>i.id===item.id?{...i,placed:true}:i);const count=state.turnCount+1;const done=items.every(i=>i.placed);setState({...state,grid,items,turn:me==="gu"?"li":"gu",turnCount:count,eventIndex:Math.min(2,Math.floor(count/2)),phase:done?"done":"playing",message:done?"Mala fechada. Vocês levaram o essencial.":BAG_EVENTS[Math.min(2,Math.floor(count/2))]});setSelected(null);setRotation(0);};
 const score=useMemo(()=>state.items.filter(i=>i.placed).reduce((a,i)=>a+i.points,0),[state.items]);
 return <Gate peerOnline={peerOnline} ready={state.ready} me={me} onReady={ready} started={state.phase!=="lobby"} onStart={start} title="Mala Tetris" subtitle="Encaixem tudo numa única mala."><div className="mx-auto max-w-3xl space-y-4 p-4 pb-8"><div className="flex justify-between rounded-2xl border border-white/10 bg-white/[0.04] p-4"><div><p className="text-xs text-white/40">turno</p><p className="font-black">{state.phase==="done"?"Fim":state.turn===me?"Sua vez":"Vez do outro jogador"}</p></div><p className="font-black text-fuchsia-300">Pontos {score}</p></div>{state.phase!=="done"&&<div className="rounded-2xl border border-amber-300/20 bg-amber-300/10 p-4"><p className="text-xs uppercase tracking-widest text-amber-200">situação</p><p className="font-bold mt-1">{BAG_EVENTS[state.eventIndex]}</p></div>}<div className="grid gap-4 md:grid-cols-[1fr_280px]"><div className="rounded-3xl border border-white/10 bg-[#111318] p-4"><div className="grid grid-cols-8 gap-1 rounded-2xl bg-black/30 p-2">{state.grid.map((cell,i)=><button key={i} onClick={()=>place(i)} className={"aspect-square rounded-md border text-[9px] font-black "+(cell?"border-fuchsia-300/30 bg-fuchsia-500/50":"border-white/5 bg-white/[0.03]")}>{cell?state.items.find(x=>x.id===cell)?.icon:""}</button>)}</div>{state.phase==="done"&&<div className="mt-4 rounded-2xl bg-emerald-400/10 p-4 text-center"><p className="font-black text-emerald-300">Viagem pronta</p><p className="text-sm text-white/60 mt-1">Vocês esqueceram o carregador. Claro.</p></div>}</div><div className="rounded-3xl border border-white/10 bg-white/[0.04] p-4"><div className="flex justify-between"><p className="font-black">Seus objetos</p><button onClick={()=>setRotation(r=>(r+1)%4)} className="rounded-xl bg-white/10 p-2"><RotateCcw size={16}/></button></div><div className="mt-3 space-y-2">{state.items.filter(i=>i.owner===me&&!i.placed).map(i=><button key={i.id} onClick={()=>setSelected(i.id)} disabled={state.turn!==me} className={"w-full rounded-2xl border p-3 text-left "+(selected===i.id?"border-fuchsia-400 bg-fuchsia-500/10":"border-white/10 bg-black/20")+" "+(state.turn!==me?"opacity-40":"")}><p className="font-bold">{i.name}</p><p className="text-xs text-white/40">{i.shape.length} blocos</p></button>)}</div>{selected&&<p className="mt-3 text-xs text-fuchsia-200">Selecione uma célula da mala para encaixar.</p>}</div></div></div></Gate>;
}

/* ACAMPAMENTO */
type CampState={phase:"lobby"|"day"|"night"|"done";ready:Ready;day:number;wood:number;food:number;water:number;fire:number;shelter:number;explorerAction:boolean;baseAction:boolean;message:string;danger:boolean};
const campInitial:CampState={phase:"lobby",ready:{gu:false,li:false},day:1,wood:3,food:3,water:3,fire:4,shelter:1,explorerAction:false,baseAction:false,message:"Sobrevivam a três noites.",danger:false};

export function Acampamento({me}:{me:Me}){
 const {state,setState,peerOnline}=useGameChannel<CampState>("acampamento",me,campInitial);
 const ready=()=>setState(s=>({...s,ready:{...s.ready,[me]:true}}));
 const start=()=>{if(peerOnline&&state.ready.gu&&state.ready.li)setState({...state,phase:"day",message:"BB Gu explora. BB Li cuida da base."});};
 const act=()=>{if(state.phase!=="day")return;if(me==="gu"&&!state.explorerAction)setState({...state,wood:state.wood+2,food:state.food+1,water:state.water+1,explorerAction:true,message:"Você voltou da floresta com recursos."});if(me==="li"&&!state.baseAction)setState({...state,fire:Math.min(8,state.fire+2),shelter:Math.min(3,state.shelter+1),baseAction:true,message:"A base está mais protegida e a fogueira está forte."});};
 const next=()=>{if(!state.explorerAction||!state.baseAction)return;const food=Math.max(0,state.food-1),water=Math.max(0,state.water-1),fire=Math.max(0,state.fire-1),lost=food===0||water===0||fire===0;if(lost||state.day===3)setState({...state,phase:"done",food,water,fire,danger:state.day===2,message:lost?"A expedição terminou antes do resgate.":"Vocês sobreviveram às três noites."});else setState({...state,phase:"night",food,water,fire,danger:state.day===2,message:state.day===2?"Você ouviu algo na floresta. Só a base consegue enxergar.":"A noite passou. Mantenham tudo funcionando."});};
 const wake=()=>setState({...state,day:state.day+1,phase:"day",explorerAction:false,baseAction:false,danger:false,message:"Novo dia. Façam suas tarefas."});
 return <Gate peerOnline={peerOnline} ready={state.ready} me={me} onReady={ready} started={state.phase!=="lobby"} onStart={start} title="Acampamento" subtitle="Um explora. O outro cuida da base e vê coisas que o explorador não vê."><div className="mx-auto max-w-2xl space-y-4 p-4 pb-8"><div className="grid grid-cols-2 md:grid-cols-5 gap-2">{[["Madeira",state.wood],["Comida",state.food],["Água",state.water],["Fogo",state.fire],["Abrigo",state.shelter]].map(x=><div key={String(x[0])} className="rounded-2xl border border-white/10 bg-white/[0.04] p-3"><p className="text-[10px] text-white/40">{x[0]}</p><p className="text-xl font-black">{x[1]}</p></div>)}</div><div className="rounded-3xl border border-white/10 bg-gradient-to-br from-emerald-950 to-slate-950 p-6"><div className="flex items-center gap-3"><TentTree className="text-emerald-300" size={28}/><div><p className="text-xs text-white/40">Dia {state.day}</p><p className="text-xl font-black">{state.phase==="night"?"Noite":state.phase==="done"?"Fim":"Acampamento"}</p></div></div><p className="text-center text-lg font-bold mt-5">{state.message}</p>{state.danger&&<div className="mt-4 rounded-2xl bg-red-500/10 p-4 text-center"><TreePine className="mx-auto mb-2 text-red-300" size={22}/><p className="font-bold">Só quem está na base viu o movimento.</p></div>}</div>{state.phase==="day"&&<div className="grid md:grid-cols-2 gap-3"><button onClick={act} disabled={me!=="gu"||state.explorerAction} className="rounded-3xl border border-white/10 bg-white/[0.05] p-5 text-left disabled:opacity-40"><Compass className="mb-3 text-sky-300" size={24}/><p className="font-black">Explorar</p><p className="text-xs text-white/50 mt-1">Encontrar madeira, comida e água.</p></button><button onClick={act} disabled={me!=="li"||state.baseAction} className="rounded-3xl border border-white/10 bg-white/[0.05] p-5 text-left disabled:opacity-40"><Campfire className="mb-3 text-orange-300" size={24}/><p className="font-black">Cuidar da base</p><p className="text-xs text-white/50 mt-1">Reforçar fogo e abrigo.</p></button></div>}{state.phase==="day"&&state.explorerAction&&state.baseAction&&<button onClick={next} className="w-full rounded-2xl bg-gradient-to-r from-emerald-500 to-teal-600 py-3 font-black">Passar a noite</button>}{state.phase==="night"&&<button onClick={wake} className="w-full rounded-2xl bg-white/10 py-3 font-black">Amanhecer</button>}{state.phase==="done"&&<div className="rounded-3xl bg-emerald-400/10 p-6 text-center"><Flame className="mx-auto mb-2 text-orange-300" size={28}/><p className="font-black">{state.food>0&&state.water>0&&state.fire>0?"Resgate concluído":"A floresta venceu desta vez"}</p></div>}</div></Gate>;
}

/* ALIENÍGENA */
type AlienState={phase:"lobby"|"playing"|"vote"|"done";ready:Ready;round:number;alien:number;asked:number|null;answers:string[];votes:{gu:number|null;li:number|null};result:string};
const passengers=["Maya","Rui","Léo","Nora"];
const questions=["De onde você veio?","O que faria num domingo?","O que levaria numa viagem?","O que mais chama sua atenção numa cidade?","Qual comida escolheria numa festa?"];
const alienInitial:AlienState={phase:"lobby",ready:{gu:false,li:false},round:1,alien:0,asked:null,answers:[],votes:{gu:null,li:null},result:""};

function alienAnswer(alien:number,asked:number,round:number){if(asked===alien)return ["Eu só queria chegar ao meu destino.","Eu gosto de observar as pessoas.","Eu levaria uma coisa simples.","Eu reparo bastante nos lugares.","Eu escolheria algo fácil de compartilhar."][round-1];return [["Vim de outra cidade.","Gosto de cozinhar.","Levaria uma câmera.","Gosto de prédios antigos.","Eu escolheria algo doce."],[ "Vim visitar amigos.","Gosto de testar receitas.","Levaria um caderno.","Gosto de procurar restaurantes.","Eu escolheria algo salgado."],[ "Vim estudar.","Gosto de jogar.","Levaria fones.","Gosto de reparar nas pessoas.","Eu escolheria pizza."],[ "Vim fotografar.","Gosto de sair cedo.","Levaria uma câmera.","Gosto de procurar paisagens.","Eu escolheria um bolo."]][asked][round-1];}

export function AlienBancoTras({me}:{me:Me}){
 const {state,setState,peerOnline}=useGameChannel<AlienState>("alien-banco",me,alienInitial);const [asked,setAsked]=useState(0);
 const ready=()=>setState(s=>({...s,ready:{...s.ready,[me]:true}}));const start=()=>{if(peerOnline&&state.ready.gu&&state.ready.li)setState({...state,phase:"playing",alien:Math.floor(Math.random()*4),round:1,asked:0,answers:[]});};
 const inspect=()=>{const a=alienAnswer(state.alien,asked,state.round);setState({...state,asked,answers:[...state.answers,a]});};
 const next=()=>{if(state.round>=5)setState({...state,phase:"vote"});else setState({...state,round:state.round+1,asked:null,answers:[]});};
 const vote=(v:number)=>{const votes={...state.votes,[me]:v};if(votes.gu!==null&&votes.li!==null)setState({...state,votes,phase:"done",result:votes.gu===state.alien&&votes.li===state.alien?"Vocês identificaram o alienígena.":"O alienígena passou despercebido."});else setState({...state,votes});};
 return <Gate peerOnline={peerOnline} ready={state.ready} me={me} onReady={ready} started={state.phase!=="lobby"} onStart={start} title="Alienígena no banco de trás" subtitle="O motorista pergunta. O passageiro de trás observa. Um deles não é humano."><div className="mx-auto max-w-2xl space-y-4 p-4 pb-8">{state.phase==="playing"&&<><div className="rounded-3xl border border-white/10 bg-white/[0.04] p-5"><div className="flex items-center gap-3"><Car className="text-cyan-300" size={28}/><div><p className="text-xs text-white/40">Rodada {state.round}/5</p><p className="font-black">{questions[state.round-1]}</p></div></div><div className="mt-5 grid grid-cols-2 gap-2">{passengers.map((p,i)=><button key={p} onClick={()=>setAsked(i)} className={"rounded-2xl border p-4 text-left "+(asked===i?"border-cyan-300 bg-cyan-400/10":"border-white/10 bg-black/20")}><p className="font-bold">{p}</p><p className="text-xs text-white/40">{me==="li"?"Observe os movimentos e escolha um suspeito.":"Faça a pergunta a este passageiro."}</p></button>)}</div></div><button onClick={inspect} disabled={asked===null} className="w-full rounded-2xl bg-gradient-to-r from-cyan-500 to-violet-600 py-3 font-black">{me==="gu"?"Perguntar ao passageiro":"Observar passageiro"}</button>{state.answers.length>0&&<div className="rounded-3xl border border-white/10 bg-black/20 p-5"><p className="text-xs uppercase tracking-widest text-white/40">Resposta / observação</p><p className="mt-2 font-semibold">{state.answers[state.answers.length-1]}</p></div>} {state.answers.length>0&&<button onClick={next} className="w-full rounded-2xl bg-white/10 py-3 font-black">{state.round>=5?"Ir para votação":"Próxima rodada"}</button>}</>}{state.phase==="vote"&&<div className="rounded-3xl border border-white/10 bg-white/[0.04] p-5"><p className="font-black text-lg">Quem é o alienígena?</p><div className="grid grid-cols-2 gap-2 mt-4">{passengers.map((p,i)=><button key={p} onClick={()=>vote(i)} className={"rounded-2xl border p-4 "+(state.votes[me]===i?"border-amber-300 bg-amber-400/10":"border-white/10 bg-black/20")}>{p}</button>)}</div></div>}{state.phase==="done"&&<div className="rounded-3xl border border-emerald-300/20 bg-emerald-400/10 p-6 text-center"><Shield className="mx-auto mb-3 text-emerald-300" size={30}/><p className="font-black text-lg">{state.result}</p></div>}</div></Gate>;
}

/* FEITIÇO ERRADO */
type SpellState={phase:"lobby"|"playing"|"done";ready:Ready;round:number;score:number;target:string[];message:string};
const SPELLS=[["SOL","VENTO"],["GELO","VENTO"],["PEDRA","VENTO"],["SOL","PEDRA"],["LUZ","FLORESTA"],["GELO","PEDRA"]];
const spellNames=["SOL","GELO","VENTO","PEDRA","FLORESTA","LUZ"];
const spellInitial:SpellState={phase:"lobby",ready:{gu:false,li:false},round:1,score:0,target:SPELLS[0],message:""};

export function FeiticoErrado({me}:{me:Me}){
 const {state,setState,peerOnline}=useGameChannel<SpellState>("feitico-errado",me,spellInitial);const [picked,setPicked]=useState<string[]>([]);
 const ready=()=>setState(s=>({...s,ready:{...s.ready,[me]:true}}));const start=()=>{if(peerOnline&&state.ready.gu&&state.ready.li)setState({...state,phase:"playing",round:1,score:0,target:SPELLS[0],message:"Conversem: cada jogador enxerga uma parte do livro."});};
 const cast=()=>{if(picked.length!==2)return;const key=picked.slice().sort().join("+"),target=state.target.slice().sort().join("+"),hit=key===target;const next=state.round+1;setState({...state,score:state.score+(hit?2:0),round:next,phase:next>5?"done":"playing",target:SPELLS[(next-1)%SPELLS.length],message:hit?"O feitiço funcionou. Vocês resolveram a situação.":"O feitiço saiu errado. Tentem outra combinação."});setPicked([]);};
 return <Gate peerOnline={peerOnline} ready={state.ready} me={me} onReady={ready} started={state.phase!=="lobby"} onStart={start} title="Feitiço errado" subtitle="Dois aprendizes precisam descobrir combinações sem conhecer o livro inteiro."><div className="mx-auto max-w-2xl space-y-4 p-4 pb-8">{state.phase==="playing"&&<><div className="rounded-3xl border border-white/10 bg-gradient-to-br from-violet-950 to-slate-950 p-6"><div className="flex items-center gap-3"><WandSparkles className="text-violet-300" size={28}/><div><p className="text-xs text-white/40">Problema {state.round}/5</p><p className="font-black">Descubram o feitiço que resolve a situação.</p></div></div><div className="mt-5 rounded-2xl bg-black/20 p-4"><p className="text-xs text-white/40">Pistas do seu fragmento</p><p className="mt-1 text-sm text-white/70">{me==="gu"?"SOL aquece. VENTO movimenta. PEDRA protege.":"GELO resfria. FLORESTA cria vida. LUZ revela caminhos."}</p></div></div><div className="grid grid-cols-2 gap-3">{spellNames.map(s=><button key={s} onClick={()=>setPicked(p=>p.includes(s)?p.filter(x=>x!==s):p.length<2?[...p,s]:p)} className={"rounded-2xl border p-4 font-black "+(picked.includes(s)?"border-violet-300 bg-violet-400/15":"border-white/10 bg-white/[0.04]")}>{s}</button>)}</div><p className="rounded-2xl bg-black/20 p-4 text-sm text-white/60">Combinação: <b className="text-white">{picked.length?picked.join(" + "):"nenhuma"}</b></p><button onClick={cast} disabled={picked.length!==2} className="w-full rounded-2xl bg-gradient-to-r from-violet-500 to-fuchsia-600 py-3 font-black disabled:opacity-30">Lançar feitiço</button><div className="rounded-2xl bg-black/20 p-4 text-sm text-white/60">{state.message}</div></>}{state.phase==="done"&&<div className="rounded-3xl border border-violet-300/20 bg-violet-500/10 p-6 text-center"><p className="text-3xl font-black">{state.score} pontos</p><p className="mt-2 text-white/60">{state.message}</p></div>}</div></Gate>;
}
