export const SPECTRA_EXTRA: [string, string][] = [
  ["salgado", "doce"], ["barato", "caro"], ["silencioso", "barulhento"], ["feio", "lindo"], ["chato", "divertido"],
  ["lento", "rápido"], ["inútil", "essencial"], ["frio", "quente"], ["mole", "duro"], ["pequeno", "gigante"],
  ["comida de dia", "comida de madrugada"], ["programa de casal ruim", "programa de casal perfeito"],
  ["presente ruim", "presente incrível"], ["filme de chorar", "filme de rir"], ["série esquecível", "série viciante"],
  ["música de academia", "música de dormir"], ["música brega", "música chique"], ["fofo", "assustador"],
  ["coisa de criança", "coisa de idoso"], ["fácil de cozinhar", "difícil de cozinhar"], ["saudável", "besteira total"],
  ["lugar pra ir sozinho", "lugar pra ir em casal"], ["viagem de praia", "viagem de frio"], ["superestimado", "subestimado"],
  ["romântico", "nada romântico"], ["vergonhoso", "orgulhoso"], ["perigoso", "seguro"], ["sujo", "limpo"],
  ["ruim de beijar depois", "ótimo de beijar depois"], ["pet ruim", "pet perfeito"], ["superpoder inútil", "superpoder incrível"],
  ["personagem vilão", "personagem herói"], ["anime chato", "anime obra-prima"], ["jogo fácil", "jogo impossível"],
  ["passeio de domingo ruim", "domingo perfeito"], ["date barato", "date luxuoso"], ["nojento", "delicioso"],
  ["cheiro ruim", "cheiro bom"], ["normal", "esquisito"], ["coisa de rico", "coisa de pobre"], ["calmo", "estressante"],
  ["moderno", "antigo"], ["natural", "artificial"], ["rua", "casa"], ["manhã", "noite"], ["verão", "inverno"],
  ["preguiçoso", "produtivo"], ["fofo de dar abraço", "fofo de apertar"], ["tímido", "extrovertido"],
  ["coisa que eu faria", "coisa que eu nunca faria"], ["coisa de bb gu", "coisa de bb li"], ["sonho pequeno", "sonho enorme"],
  ["mico leve", "mico épico"], ["apelido fofo", "apelido ridículo"], ["roupa de ficar em casa", "roupa de festa"],
  ["comida de hospital", "comida de restaurante chique"], ["discussão boba", "discussão séria"], ["planejado", "improvisado"],
  ["fácil de perdoar", "imperdoável"], ["inofensivo", "mortal"], ["clichê", "original"], ["infantil", "maduro"],
  ["péssimo cantor", "cantor perfeito"], ["sabor ruim de sorvete", "melhor sabor de sorvete"], ["lanche ruim", "lanche top"],
  ["emoji sem graça", "emoji perfeito"], ["casa pequena", "mansão"], ["carro feio", "carro dos sonhos"],
  ["acordar cedo", "dormir tarde"], ["fácil de esquecer", "inesquecível"], ["frágil", "indestrutível"],
  ["esporte chato", "esporte emocionante"], ["profissão chata", "profissão dos sonhos"], ["cidade feia", "cidade linda"],
  ["filme infantil", "filme adulto"], ["meme velho", "meme novo"], ["engraçado sem querer", "engraçado de propósito"],
  ["coisa que dá sono", "coisa que dá energia"], ["superfofo", "nada fofo"], ["cafona", "estiloso"],
  ["desnecessário", "indispensável na viagem"], ["melhor de dia", "melhor de noite"], ["melhor sozinho", "melhor junto"],
];
