export const VERDADES = [
  "Qual foi a primeira coisa que você pensou de mim?",
  "Qual foi a mentirinha mais boba que você já me contou?",
  "O que mais te dá ciúme?",
  "Qual momento nosso você repetiria hoje?",
  "O que você mais sente falta quando estamos longe?",
  "Qual foi a vez que você mais riu comigo?",
  "Tem algo que você quis me dizer e não disse?",
  "Qual é o seu plano secreto pra gente?",
  "Quando você percebeu que gostava de mim?",
  "Qual foi o nosso momento mais constrangedor?",
  "O que você mudaria em mim se pudesse?",
  "Qual é a sua memória favorita comigo?",
  "Qual música te lembra de mim?",
  "Já sonhou comigo? Conta como foi.",
  "Qual foi a coisa mais fofa que eu já fiz por você?",
  "Qual apelido meu você mais gosta?",
  "O que te deixou nervoso(a) no nosso primeiro encontro?",
  "Qual é o seu maior medo sobre nós?",
  "Já ficou com raiva de mim sem eu saber? Por quê?",
  "Qual foi a última vez que você chorou?",
  "Qual é o seu maior sonho de vida?",
  "O que você nunca contou pra ninguém?",
  "Qual foi a maior vergonha que você já passou?",
  "Qual parte do meu corpo você acha mais bonita?",
  "Qual roupa minha você mais gosta?",
  "O que te faz se apaixonar mais por mim?",
  "Se pudesse viajar comigo amanhã, pra onde seria?",
  "Qual foi a coisa mais louca que você já fez?",
  "Quem foi seu primeiro crush?",
  "Qual é o seu maior defeito?",
  "Qual é a sua maior qualidade?",
  "O que você acha que eu penso de você?",
  "Qual é a coisa que mais te irrita em mim?",
  "Qual é a coisa que mais te irrita no mundo?",
  "Você já stalkeou meu perfil antes da gente se falar?",
  "O que você falou de mim pros seus amigos no começo?",
  "Qual foi a sua primeira impressão da minha voz?",
  "Qual é o seu lugar favorito no mundo?",
  "Se ganhasse na loteria, qual a primeira coisa que faria?",
  "Qual é a comida que você comeria pra sempre?",
  "Qual filme você assistiria comigo mil vezes?",
  "Você acredita em alma gêmea?",
  "Como você imagina a gente daqui a 5 anos?",
  "Quantos filhos você quer ter?",
  "Qual nome você daria pra um filho nosso?",
  "Qual bicho de estimação a gente teria?",
  "Como seria nossa casa dos sonhos?",
  "Qual foi a última coisa que você pesquisou no Google?",
  "Qual é a última foto da sua galeria?",
  "Qual app você mais usa escondido?",
  "Qual o seu hábito mais estranho?",
  "Você fala sozinho(a)?",
  "Qual foi a última mentira que você contou pra alguém?",
  "Você já fingiu estar doente pra faltar aula?",
  "Qual matéria você mais odeia?",
  "Qual professor você mais gostava?",
  "Qual foi a sua pior nota?",
  "O que você faz quando está triste?",
  "O que sempre te faz sorrir?",
  "Qual é o seu maior arrependimento?",
  "Qual foi o melhor presente que você já ganhou?",
  "Qual presente você queria ganhar de mim?",
  "O que você acha mais romântico?",
  "Qual o encontro perfeito pra você?",
  "Você prefere carinho ou beijo?",
  "Qual foi o melhor beijo da sua vida?",
  "Qual é o seu perfume favorito em mim?",
  "Você tem algum ciúme bobo que nunca falou?",
  "Qual é o seu maior medo na vida?",
  "Qual é a sua fobia mais estranha?",
  "Qual é seu talento escondido?",
  "Se você fosse um personagem de anime, quem seria?",
  "E eu, seria qual personagem?",
  "Qual super poder você gostaria de ter?",
  "O que você faria se ficasse invisível por um dia?",
  "Qual celebridade você acha mais bonita?",
  "Qual celebridade você acha parecida comigo?",
  "Qual é a coisa mais infantil que você ainda faz?",
  "Você dorme com bicho de pelúcia?",
  "Qual o seu desenho animado favorito da infância?",
  "Qual foi o pior corte de cabelo que você já teve?",
  "Qual é a sua mania quando está nervoso(a)?",
  "Você canta no banho? Qual música?",
  "Qual foi a última vez que você sentiu ciúme de mim?",
  "O que você pensa antes de dormir?",
  "Qual é a primeira coisa que você faz ao acordar?",
  "Você já leu minhas mensagens antigas de novo?",
  "Qual mensagem minha você mais gostou de receber?",
  "Qual é o nosso maior segredo?",
  "Qual promessa você quer me fazer?",
  "Qual é a sua maior insegurança?",
  "O que te deixa mais confiante?",
  "Qual é a sua cor favorita e por quê?",
  "Qual é o seu signo e você acredita nele?",
  "Qual foi a coisa mais corajosa que você já fez?",
  "Qual foi a última coisa que te deixou muito feliz?",
  "Quem você mais admira na vida?",
  "Que conselho você daria pro seu eu de 10 anos?",
  "O que você nunca faria por dinheiro?",
  "Qual lugar você quer conhecer antes de morrer?",
  "Qual foi a comida mais estranha que você já comeu?",
  "Você prefere praia ou montanha?",
  "Você prefere dia ou noite?",
  "Qual foi o último sonho que você lembra?",
  "Qual é a sua série de conforto?",
  "O que você acha que eu faço melhor que você?",
  "O que você faz melhor que eu?",
  "Se a gente brigasse, quem pediria desculpa primeiro?",
  "Qual foi a nossa briga mais boba?",
  "Qual frase minha você nunca esqueceu?",
  "Tem algo meu que você guarda de lembrança?",
  "O que você mais gosta na minha personalidade?",
  "Qual é o seu jeito favorito de receber carinho?",
  "Qual é a sua linguagem do amor?",
  "Qual foi a coisa mais difícil que você já superou?",
  "Qual é seu maior orgulho?",
  "Você já se apaixonou à primeira vista?",
  "O que você sentiu quando eu te mandei a primeira mensagem?",
  "Qual foi o momento em que você mais sentiu minha falta?",
  "O que você faria se a gente tivesse um dia inteiro juntos?",
  "Qual é a sua maior vontade agora?",
  "Qual segredo seu eu ainda não sei?",
  "Qual foi a sua fase mais vergonhosa?",
  "Qual foi a sua pior fase de roupa?",
  "Qual música você tem vergonha de gostar?",
  "Qual youtuber/tiktoker você mais assiste?",
  "Qual é o seu emoji mais usado?",
  "Qual é a coisa mais cara que você já comprou?",
  "Qual foi a última vez que você mentiu pra mim?",
  "Você prefere ganhar uma carta ou um presente?",
];

export const DESAFIOS = [
  "Manda um áudio cantando nossa música.",
  "Manda uma selfie fazendo a cara mais feia possível.",
  "Escreva uma declaração em 5 palavras.",
  "Manda uma foto do que você está fazendo agora.",
  "Imite eu falando por 10 segundos em áudio.",
  "Diga 3 coisas que ama em mim, sem pensar.",
  "Escolha um apelido novo pra mim agora.",
  "Manda um poema tosco de 2 linhas.",
  "Manda um áudio falando com voz de bebê.",
  "Manda uma selfie com o cabelo todo bagunçado.",
  "Escreva meu nome com a mão que você não usa e manda foto.",
  "Fala 'eu te amo' em 3 idiomas diferentes em áudio.",
  "Manda a última foto da sua galeria.",
  "Faz uma careta e manda foto em 10 segundos.",
  "Manda um áudio rindo por 10 segundos sem parar.",
  "Descreva nosso primeiro encontro como narrador de futebol.",
  "Manda um áudio imitando um bicho à sua escolha.",
  "Faça um desenho de mim em 30 segundos e manda foto.",
  "Escreva uma mini história de amor com a gente de 3 frases.",
  "Manda uma foto do seu pé.",
  "Manda uma selfie fazendo biquinho.",
  "Cante o refrão de uma música da Anitta em áudio.",
  "Fala um trava-língua 3 vezes rápido em áudio.",
  "Manda uma foto da vista da sua janela.",
  "Escreva 10 elogios pra mim sem repetir.",
  "Manda um áudio sussurrando algo fofo.",
  "Mude sua foto de perfil do chat por 1 hora pra uma que eu escolher.",
  "Me conta uma piada ruim em áudio.",
  "Manda um áudio fazendo uma declaração dramática de novela.",
  "Imite um personagem de anime em áudio.",
  "Manda uma foto segurando algo que te lembra de mim.",
  "Escreva uma mensagem só com emojis contando seu dia.",
  "Faz uma dancinha e descreve cada passo em texto.",
  "Manda um áudio dizendo meu nome de 5 jeitos diferentes.",
  "Dá uma nota de 0 a 10 pra minha última foto e justifica.",
  "Escolha uma música pra ser 'nossa' agora e manda o nome.",
  "Manda uma selfie com a luz apagada e só a tela iluminando.",
  "Escreva um acróstico com meu nome.",
  "Manda a foto mais antiga que você tem no celular.",
  "Faça 10 polichinelos e manda áudio ofegante.",
  "Fala com sotaque carioca por 3 mensagens seguidas.",
  "Fala com sotaque nordestino num áudio de 10 segundos.",
  "Fala com sotaque gaúcho num áudio de 10 segundos.",
  "Manda um print da sua tela inicial.",
  "Manda um print das suas músicas mais tocadas.",
  "Escreva o que você faria se estivesse do meu lado agora.",
  "Manda um áudio cantando parabéns pra mim, mesmo não sendo meu aniversário.",
  "Invente uma música de 4 versos sobre mim.",
  "Manda uma foto da sua expressão de 'surpresa'.",
  "Manda uma foto fazendo coração com as mãos.",
  "Responda as próximas 3 mensagens só com rimas.",
  "Diga uma qualidade minha pra cada letra de 'amor'.",
  "Manda um áudio imitando um locutor de rádio.",
  "Manda um áudio contando como foi seu dia como se fosse um jornal.",
  "Escolha uma figurinha que me representa e manda.",
  "Escreva uma carta de amor de 3 linhas no estilo medieval.",
  "Manda uma selfie com uma coisa na cabeça.",
  "Manda foto do seu lanche favorito (ou do que tiver na geladeira).",
  "Escreva sua lista de 3 desejos pra gente.",
  "Fala uma frase em inglês com a pior pronúncia possível.",
  "Manda um áudio assobiando uma música pra eu adivinhar.",
  "Descreva meu sorriso em uma frase poética.",
  "Faz uma pose de modelo e manda foto.",
  "Manda uma foto do seu sapato favorito.",
  "Me conta um segredo bobo que ninguém sabe.",
  "Faça uma avaliação de 5 estrelas sobre mim como se eu fosse um produto.",
  "Escreva o roteiro do nosso próximo encontro.",
  "Manda um áudio com a sua risada mais falsa.",
  "Manda uma foto do seu cantinho favorito da casa.",
  "Escolha um filme pra gente ver juntos e justifique.",
  "Fique 3 minutos sem mandar emoji.",
  "Descreva como você me vê em 3 palavras.",
  "Manda um áudio contando um sonho maluco que você inventar agora.",
  "Escreva meu nome de trás pra frente e crie um significado.",
  "Manda uma selfie com a cara mais séria do mundo.",
  "Manda uma foto do céu agora.",
  "Imite um vendedor de praia vendendo 'eu' em áudio.",
  "Manda um áudio fazendo beatbox.",
  "Escreva um tweet declarando seu amor como influencer.",
  "Faça um desenho da gente com bonequinhos e manda foto.",
  "Dê um nome de casal pra gente.",
  "Manda a figurinha mais aleatória que você tiver.",
  "Faça um áudio de 15 segundos me convencendo a te dar um beijo.",
  "Escreva o horóscopo de hoje pra mim.",
  "Manda uma foto do seu reflexo em algum lugar.",
  "Fale 5 coisas que você faria num domingo comigo.",
  "Manda um áudio cantando uma música infantil.",
  "Escreva uma mensagem de bom dia pra eu ler amanhã.",
  "Manda uma foto usando uma roupa minha ou algo que eu te dei.",
  "Faz um vídeo de 3 segundos acenando pra mim.",
  "Conta a história de como a gente se conheceu em 20 palavras.",
  "Escolha um anime pra gente assistir juntos.",
  "Manda uma selfie de olhos fechados.",
  "Manda um áudio fazendo a voz do Pato Donald.",
  "Invente um grito de guerra do nosso casal.",
  "Diga qual seria meu nome se eu fosse um pokémon.",
  "Manda um áudio falando 'eu sou o(a) mais bonito(a) do mundo' com confiança.",
  "Escreva uma receita de 'como fazer um namorado(a) feliz'.",
  "Manda uma foto com a língua pra fora.",
  "Faça uma pergunta de verdade que você morre de vontade de saber.",
  "Manda o print da última conversa que você teve (fora a nossa).",
  "Descreva o seu look agora em detalhes de desfile de moda.",
  "Mande uma foto de algo azul que estiver perto.",
  "Manda um áudio de 10 segundos só dizendo 'saudade'.",
  "Faça uma lista das 5 melhores fotos nossas.",
  "Escolha um emoji que vai ser 'nosso' a partir de hoje.",
  "Manda um áudio imitando um youtuber famoso.",
  "Deixe eu escolher o próximo papel de parede do chat.",
  "Mande uma foto do seu travesseiro.",
  "Escreva 3 regras do nosso namoro.",
  "Manda um áudio narrando o que você está vendo agora.",
  "Fale uma cantada bem ruim.",
  "Fale a cantada mais romântica que souber.",
  "Manda uma foto fazendo sinal de paz e amor.",
  "Descreva o nosso futuro em 1 frase.",
  "Mande 5 figurinhas seguidas sem texto.",
  "Faça uma voz de vilão e me ameace com carinho em áudio.",
  "Escreva o que você mais gosta em cada dia da semana comigo.",
  "Manda a foto mais recente que você tirou de si mesmo(a).",
  "Faça um áudio chorando de mentirinha por 5 segundos.",
  "Diga qual série seria a nossa história de amor.",
];
