/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZzDolltestRouteImport } from './routes/zz-dolltest'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MinhaListaRouteImport } from './routes/minha-lista'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnimeAnimeIdRouteImport } from './routes/anime.$animeId'

const ZzDolltestRoute = ZzDolltestRouteImport.update({
  id: '/zz-dolltest',
  path: '/zz-dolltest',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaListaRoute = MinhaListaRouteImport.update({
  id: '/minha-lista',
  path: '/minha-lista',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeAnimeIdRoute = AnimeAnimeIdRouteImport.update({
  id: '/anime/$animeId',
  path: '/anime/$animeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explorar': typeof ExplorarRoute
  '/minha-lista': typeof MinhaListaRoute
  '/perfil': typeof PerfilRoute
  '/zz-dolltest': typeof ZzDolltestRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explorar': typeof ExplorarRoute
  '/minha-lista': typeof MinhaListaRoute
  '/perfil': typeof PerfilRoute
  '/zz-dolltest': typeof ZzDolltestRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explorar': typeof ExplorarRoute
  '/minha-lista': typeof MinhaListaRoute
  '/perfil': typeof PerfilRoute
  '/zz-dolltest': typeof ZzDolltestRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explorar'
    | '/minha-lista'
    | '/perfil'
    | '/zz-dolltest'
    | '/anime/$animeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explorar'
    | '/minha-lista'
    | '/perfil'
    | '/zz-dolltest'
    | '/anime/$animeId'
  id:
    | '__root__'
    | '/'
    | '/explorar'
    | '/minha-lista'
    | '/perfil'
    | '/zz-dolltest'
    | '/anime/$animeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExplorarRoute: typeof ExplorarRoute
  MinhaListaRoute: typeof MinhaListaRoute
  PerfilRoute: typeof PerfilRoute
  ZzDolltestRoute: typeof ZzDolltestRoute
  AnimeAnimeIdRoute: typeof AnimeAnimeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zz-dolltest': {
      id: '/zz-dolltest'
      path: '/zz-dolltest'
      fullPath: '/zz-dolltest'
      preLoaderRoute: typeof ZzDolltestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-lista': {
      id: '/minha-lista'
      path: '/minha-lista'
      fullPath: '/minha-lista'
      preLoaderRoute: typeof MinhaListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$animeId': {
      id: '/anime/$animeId'
      path: '/anime/$animeId'
      fullPath: '/anime/$animeId'
      preLoaderRoute: typeof AnimeAnimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExplorarRoute: ExplorarRoute,
  MinhaListaRoute: MinhaListaRoute,
  PerfilRoute: PerfilRoute,
  ZzDolltestRoute: ZzDolltestRoute,
  AnimeAnimeIdRoute: AnimeAnimeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
